// ═══════════════════════════════════════════════════════════════════════════════
// ASSET CLASS REGISTRY
// Single source of truth. Adding a new entry here makes it work everywhere:
// map heat blobs, marker icons, sidebar filters, detail panel labels,
// revenue breakdown, demographic key metrics, and portfolio stats.
// ═══════════════════════════════════════════════════════════════════════════════

export interface AssetRegistryEntry {
  label: string;
  icon: string;
  color: string;
  group: string;
  sizeLabel: string;
  occLabel: string;
  priceUnit: string;
  rev: [string, string, string];
  demandKey: string;
  radarLabels?: string[];
}

export const ASSET_REGISTRY: Record<string, AssetRegistryEntry> = {
  // ── WATERFRONT ──────────────────────────────────────────────────────────────
  marina:           { label:"Marina",               icon:"⚓", color:"#00d4ff", group:"Waterfront",
                      sizeLabel:"Slips",       occLabel:"Slip Occ %",    priceUnit:"Slip",
                      rev:["Fuel Revenue","Storage Revenue","Service Revenue"],
                      demandKey:"Boat Ownership %" },
  dry_stack:        { label:"Dry Stack / Boatyard",  icon:"🚢", color:"#06b6d4", group:"Waterfront",
                      sizeLabel:"Rack Units",  occLabel:"Rack Occ %",    priceUnit:"Rack",
                      rev:["Storage Fees","Launch Fees","Service Revenue"],
                      demandKey:"Boat Ownership %" },
  yacht_club:       { label:"Yacht Club",            icon:"⛵", color:"#38bdf8", group:"Waterfront",
                      sizeLabel:"Slips",       occLabel:"Membership Occ",priceUnit:"Slip",
                      rev:["Membership Dues","Slip Fees","F&B Revenue"],
                      demandKey:"HH Boat Ownership %" },
  waterfront_resort:{ label:"Waterfront Resort",     icon:"🌊", color:"#0ea5e9", group:"Waterfront",
                      sizeLabel:"Keys",        occLabel:"Occ %",         priceUnit:"Key",
                      rev:["Room Revenue","Marina Fees","F&B Revenue"],
                      demandKey:"Tourism Index" },
  boat_rental:      { label:"Boat Rental / Charter",  icon:"🛥️", color:"#22d3ee", group:"Waterfront",
                      sizeLabel:"Vessels",     occLabel:"Utilization %", priceUnit:"Vessel",
                      rev:["Charter Revenue","Rental Revenue","Fuel/Ancillary"],
                      demandKey:"Visitor Spend Index" },

  // ── HOSPITALITY ─────────────────────────────────────────────────────────────
  hotel:            { label:"Hotel",                 icon:"🏨", color:"#a78bfa", group:"Hospitality",
                      sizeLabel:"Keys",        occLabel:"Occ % / RevPAR",priceUnit:"Key",
                      rev:["Room Revenue","F&B Revenue","Ancillary"],
                      demandKey:"Tourism Index" },
  boutique_hotel:   { label:"Boutique Hotel",        icon:"🛎️", color:"#8b5cf6", group:"Hospitality",
                      sizeLabel:"Keys",        occLabel:"Occ %",         priceUnit:"Key",
                      rev:["Room Revenue","F&B Revenue","Events Revenue"],
                      demandKey:"ADR vs Market" },
  motel:            { label:"Motel / Motor Inn",      icon:"🏩", color:"#c084fc", group:"Hospitality",
                      sizeLabel:"Keys",        occLabel:"Occ %",         priceUnit:"Key",
                      rev:["Room Revenue","Vending","Ancillary"],
                      demandKey:"Drive-by Traffic" },
  extended_stay:    { label:"Extended Stay",          icon:"🏠", color:"#e879f9", group:"Hospitality",
                      sizeLabel:"Units",       occLabel:"Occ %",         priceUnit:"Unit",
                      rev:["Weekly Room Rev","Monthly Room Rev","Ancillary"],
                      demandKey:"Corporate Demand Idx" },
  rv_park:          { label:"RV Park / Campground",   icon:"🚐", color:"#f59e0b", group:"Hospitality",
                      sizeLabel:"Sites",       occLabel:"Occ %",         priceUnit:"Site",
                      rev:["Site Rental","Hook-Ups","Store/Amenity"],
                      demandKey:"Snowbird Season %" },
  glamping:         { label:"Glamping / Eco-Resort",  icon:"⛺", color:"#fbbf24", group:"Hospitality",
                      sizeLabel:"Units",       occLabel:"Occ %",         priceUnit:"Unit",
                      rev:["Accommodation Rev","Experience Rev","F&B"],
                      demandKey:"Experiential Travel Idx" },

  // ── MULTIFAMILY / RESIDENTIAL ───────────────────────────────────────────────
  multifamily:      { label:"Multifamily",            icon:"🏢", color:"#4ade80", group:"Residential",
                      sizeLabel:"Units",       occLabel:"Occ %",         priceUnit:"Unit",
                      rev:["Rental Revenue","Parking Revenue","Ancillary"],
                      demandKey:"Renter Demand Index" },
  garden_apt:       { label:"Garden Apartments",      icon:"🌿", color:"#22c55e", group:"Residential",
                      sizeLabel:"Units",       occLabel:"Occ %",         priceUnit:"Unit",
                      rev:["Rental Revenue","Laundry/Vend","Storage"],
                      demandKey:"Rent Growth YoY %" },
  senior_housing:   { label:"Senior Housing",         icon:"👴", color:"#86efac", group:"Residential",
                      sizeLabel:"Units",       occLabel:"Occ %",         priceUnit:"Unit",
                      rev:["Rent/Care Fees","Ancillary Services","Memory Care"],
                      demandKey:"65+ Population %" },
  student_housing:  { label:"Student Housing",        icon:"🎓", color:"#bbf7d0", group:"Residential",
                      sizeLabel:"Beds",        occLabel:"Bed Occ %",     priceUnit:"Bed",
                      rev:["Bed Rental","Parking","Amenity Fees"],
                      demandKey:"Enrollment Growth %" },
  mobile_home:      { label:"Mobile Home Park",       icon:"🏘️", color:"#34d399", group:"Residential",
                      sizeLabel:"Pads",        occLabel:"Pad Occ %",     priceUnit:"Pad",
                      rev:["Pad Rent","Utility Fee","Ancillary"],
                      demandKey:"Affordable Housing Gap" },
  condo:            { label:"Condo / Townhome",       icon:"🏡", color:"#6ee7b7", group:"Residential",
                      sizeLabel:"Units",       occLabel:"Sold / Leased %",priceUnit:"Unit",
                      rev:["Sale Proceeds","HOA Income","Rental Pool"],
                      demandKey:"Median Home Price Idx" },
  single_family_sfr:{ label:"SFR Portfolio",          icon:"🏠", color:"#a7f3d0", group:"Residential",
                      sizeLabel:"Homes",       occLabel:"Occ %",         priceUnit:"Home",
                      rev:["Rental Revenue","Pet Fees","Late/Other"],
                      demandKey:"SFR Rent Growth %" },

  // ── INDUSTRIAL ──────────────────────────────────────────────────────────────
  industrial:       { label:"Industrial / Flex",      icon:"🏭", color:"#fb923c", group:"Industrial",
                      sizeLabel:"Sq Ft",       occLabel:"Leased %",      priceUnit:"Sq Ft",
                      rev:["NNN Rent","Reimbursements","Other Income"],
                      demandKey:"Industrial Vacancy %" },
  warehouse:        { label:"Warehouse / Distribution",icon:"📦", color:"#f97316", group:"Industrial",
                      sizeLabel:"Sq Ft",       occLabel:"Leased %",      priceUnit:"Sq Ft",
                      rev:["Base Rent","NNN Reimb","Other"],
                      demandKey:"Port Proximity Score" },
  cold_storage:     { label:"Cold Storage",           icon:"🧊", color:"#fed7aa", group:"Industrial",
                      sizeLabel:"Sq Ft",       occLabel:"Leased %",      priceUnit:"Sq Ft",
                      rev:["Storage Fees","Handling Fees","Ancillary"],
                      demandKey:"Food Logistics Demand" },
  self_storage:     { label:"Self Storage",           icon:"🗃️", color:"#facc15", group:"Industrial",
                      sizeLabel:"Units",       occLabel:"Occ %",         priceUnit:"Unit",
                      rev:["Storage Revenue","Insurance","Truck Rental"],
                      demandKey:"Storage Units / 1K Pop" },
  data_center:      { label:"Data Center",            icon:"🖥️", color:"#fde68a", group:"Industrial",
                      sizeLabel:"MW / Cabinets",occLabel:"Power Util %", priceUnit:"Cabinet",
                      rev:["Colocation Rev","Power Revenue","Managed Svcs"],
                      demandKey:"Cloud Demand Index" },
  truck_terminal:   { label:"Truck Terminal / Logistics",icon:"🚛",color:"#fbbf24",group:"Industrial",
                      sizeLabel:"Doors / Acres",occLabel:"Utilization %",priceUnit:"Door",
                      rev:["Docking Fees","Storage","Cross-Dock"],
                      demandKey:"Freight Traffic Index" },

  // ── OFFICE ──────────────────────────────────────────────────────────────────
  office:           { label:"Office",                 icon:"🏬", color:"#60a5fa", group:"Office",
                      sizeLabel:"Sq Ft",       occLabel:"Leased %",      priceUnit:"Sq Ft",
                      rev:["Base Rent","Parking","Ancillary"],
                      demandKey:"Office Absorption Rate" },
  medical_office:   { label:"Medical Office",         icon:"🏥", color:"#93c5fd", group:"Office",
                      sizeLabel:"Sq Ft",       occLabel:"Leased %",      priceUnit:"Sq Ft",
                      rev:["NNN Rent","Reimb","Parking"],
                      demandKey:"Healthcare Demand Idx" },
  coworking:        { label:"Co-working / Flex Office",icon:"💼", color:"#bfdbfe", group:"Office",
                      sizeLabel:"Desks / Offices",occLabel:"Util %",     priceUnit:"Desk",
                      rev:["Membership Rev","Private Office","Meeting Rooms"],
                      demandKey:"Remote Work Penetration" },
  creative_office:  { label:"Creative / Loft Office", icon:"🎨", color:"#dbeafe", group:"Office",
                      sizeLabel:"Sq Ft",       occLabel:"Leased %",      priceUnit:"Sq Ft",
                      rev:["Base Rent","Event Space","Parking"],
                      demandKey:"Creative Sector Jobs %" },

  // ── RETAIL ──────────────────────────────────────────────────────────────────
  retail:           { label:"Retail Strip",           icon:"🛍️", color:"#f472b6", group:"Retail",
                      sizeLabel:"Sq Ft",       occLabel:"Leased %",      priceUnit:"Sq Ft",
                      rev:["Base Rent","NNN Reimb","Overage Rent"],
                      demandKey:"Retail Sales PSF" },
  anchored_retail:  { label:"Anchored Shopping Ctr",  icon:"🏪", color:"#f9a8d4", group:"Retail",
                      sizeLabel:"Sq Ft",       occLabel:"Leased %",      priceUnit:"Sq Ft",
                      rev:["Anchor Rent","Inline Rent","NNN Reimb"],
                      demandKey:"Trade Area Population" },
  nnn_single_tenant:{ label:"NNN Single Tenant",      icon:"🏦", color:"#fbcfe8", group:"Retail",
                      sizeLabel:"Sq Ft",       occLabel:"Lease Term Rem.",priceUnit:"Sq Ft",
                      rev:["Base Rent","NNN Reimb","Other"],
                      demandKey:"Tenant Credit Rating" },
  car_wash:         { label:"Car Wash",               icon:"🚗", color:"#22d3ee", group:"Operating Biz",
                      sizeLabel:"Bays / Tunnels",occLabel:"Util %",      priceUnit:"Bay",
                      rev:["Wash Revenue","Membership Rev","Vending"],
                      demandKey:"Vehicles / Day" },
  gas_station:      { label:"Gas Station / C-Store",  icon:"⛽", color:"#67e8f9", group:"Operating Biz",
                      sizeLabel:"Pumps / Sq Ft",occLabel:"Traffic Index", priceUnit:"Pump",
                      rev:["Fuel Margin","C-Store Revenue","Car Wash"],
                      demandKey:"Daily Traffic Count" },
  restaurant:       { label:"Restaurant / QSR",       icon:"🍽️", color:"#fdba74", group:"Operating Biz",
                      sizeLabel:"Seats",       occLabel:"Table Turn Rate",priceUnit:"Seat",
                      rev:["Food Revenue","Beverage Rev","Catering/Other"],
                      demandKey:"Daytime Population" },
  fast_food:        { label:"Fast Food / Drive-Thru",  icon:"🍔", color:"#fca5a5", group:"Operating Biz",
                      sizeLabel:"Sq Ft",       occLabel:"Drive-Thru Spd.",priceUnit:"Sq Ft",
                      rev:["Sales Revenue","Catering","Loyalty/Digital"],
                      demandKey:"Traffic Count" },

  // ── LAND / SPECIAL PURPOSE ──────────────────────────────────────────────────
  ranchland:        { label:"Ranchland / Farm",       icon:"🌾", color:"#a3e635", group:"Land",
                      sizeLabel:"Acres",       occLabel:"Utilization %", priceUnit:"Acre",
                      rev:["Grazing/Crop Lease","Hunting Lease","Timber/Other"],
                      demandKey:"Agricultural Land Value" },
  timberland:       { label:"Timberland",             icon:"🌲", color:"#84cc16", group:"Land",
                      sizeLabel:"Acres",       occLabel:"Harvest Cycle",  priceUnit:"Acre",
                      rev:["Timber Sales","Carbon Credits","Hunting Lease"],
                      demandKey:"Timber Price Index" },
  dev_land:         { label:"Development Site",       icon:"🏗️", color:"#d9f99d", group:"Land",
                      sizeLabel:"Acres",       occLabel:"Entitlement %", priceUnit:"Acre",
                      rev:["Land Lease","Billboard/Tower","Mineral Rights"],
                      demandKey:"Permit Activity Index" },
  solar_land:       { label:"Solar / Energy Land",    icon:"☀️", color:"#fef08a", group:"Land",
                      sizeLabel:"Acres / MW",  occLabel:"Capacity Util %",priceUnit:"Acre",
                      rev:["PPA Revenue","Land Lease","SREC Credits"],
                      demandKey:"Solar Irradiance Score" },

  // ── SPECIAL PURPOSE ─────────────────────────────────────────────────────────
  parking:          { label:"Parking Garage / Lot",   icon:"🅿️", color:"#94a3b8", group:"Special Purpose",
                      sizeLabel:"Spaces",      occLabel:"Occ %",         priceUnit:"Space",
                      rev:["Hourly Revenue","Monthly Permits","Event Parking"],
                      demandKey:"CBD Parking Demand" },
  car_dealership:   { label:"Auto Dealership",        icon:"🚘", color:"#64748b", group:"Special Purpose",
                      sizeLabel:"Sq Ft / Lots",occLabel:"Inventory Turn", priceUnit:"Sq Ft",
                      rev:["Vehicle Sales","F&I Income","Service/Parts"],
                      demandKey:"Auto Sales Index" },
  church:           { label:"Church / Religious",     icon:"⛪", color:"#c8a96e", group:"Special Purpose",
                      sizeLabel:"Seats / Sq Ft",occLabel:"Congregation",  priceUnit:"Seat",
                      rev:["Tithes/Donations","Event Rental","School Fees"],
                      demandKey:"Congregation Growth" },
  school:           { label:"School / Daycare",       icon:"🏫", color:"#86efac", group:"Special Purpose",
                      sizeLabel:"Seats / Sq Ft",occLabel:"Enrollment %",  priceUnit:"Seat",
                      rev:["Tuition Revenue","Subsidy/Grant","Aftercare"],
                      demandKey:"Child Pop Under 18 %" },
  theater:          { label:"Theater / Entertainment",icon:"🎭", color:"#e879f9", group:"Special Purpose",
                      sizeLabel:"Seats",       occLabel:"Occ %",         priceUnit:"Seat",
                      rev:["Ticket Revenue","Concessions","Event Rental"],
                      demandKey:"Arts & Culture Index" },
  gym_fitness:      { label:"Gym / Fitness Center",   icon:"🏋️", color:"#4ade80", group:"Operating Biz",
                      sizeLabel:"Sq Ft / Members",occLabel:"Util %",    priceUnit:"Member",
                      rev:["Membership Dues","Personal Training","Retail"],
                      demandKey:"Fitness Penetration %" },
  laundromat:       { label:"Laundromat",             icon:"🧺", color:"#67e8f9", group:"Operating Biz",
                      sizeLabel:"Machines",    occLabel:"Util %",        priceUnit:"Machine",
                      rev:["Wash Revenue","Dry Revenue","Ancillary"],
                      demandKey:"Renter Household Density" },
  car_rental:       { label:"Car Rental",             icon:"🚙", color:"#fb923c", group:"Operating Biz",
                      sizeLabel:"Vehicles",    occLabel:"Fleet Util %",  priceUnit:"Vehicle",
                      rev:["Rental Revenue","Insurance/Fees","Ancillary"],
                      demandKey:"Airport Traffic Index" },
  mini_storage_plus:{ label:"Mini Storage + Wine",    icon:"🍷", color:"#c084fc", group:"Industrial",
                      sizeLabel:"Units",       occLabel:"Occ %",         priceUnit:"Unit",
                      rev:["Storage Fees","Climate Fees","Concierge"],
                      demandKey:"HH Income > $100K %" },
  mixed_use:        { label:"Mixed-Use",              icon:"🏙️", color:"#818cf8", group:"Commercial",
                      sizeLabel:"Sq Ft",       occLabel:"Blended Occ %", priceUnit:"Sq Ft",
                      rev:["Retail Rent","Residential Rent","Parking"],
                      demandKey:"Urban Density Score" },
  life_science:     { label:"Life Science / Lab",     icon:"🔬", color:"#7dd3fc", group:"Office",
                      sizeLabel:"Sq Ft",       occLabel:"Leased %",      priceUnit:"Sq Ft",
                      rev:["Lab Rent","NNN Reimb","Shared Services"],
                      demandKey:"Bio Cluster Proximity" },
};
