import pg from "pg";
const pool = new pg.Pool({ connectionString: process.env.DATABASE_URL });
await pool.query(`DELETE FROM crm_deals WHERE id IN ('test-closed-deal-phase1-a','test-closed-deal-phase1-b')`);
await pool.query(`DELETE FROM broker_response_samples WHERE broker_profile_id = 'test-broker-profile-phase1'`);
await pool.query(`DELETE FROM broker_follow_history WHERE broker_profile_id = 'test-broker-profile-phase1'`);
await pool.query(`DELETE FROM broker_subscriptions WHERE broker_profile_id = 'test-broker-profile-phase1'`);
await pool.query(`DELETE FROM broker_profiles WHERE id = 'test-broker-profile-phase1'`);
await pool.query(`DELETE FROM broker_registrations WHERE id = 'test-broker-reg-phase1'`);
await pool.query(`DELETE FROM users WHERE id = 'test-broker-user-phase1'`);
const r = await pool.query(`SELECT COUNT(*)::int AS c FROM broker_profiles WHERE id = 'test-broker-profile-phase1'`);
console.log("Remaining test rows:", r.rows[0].c);
await pool.end();
