#!/bin/bash
# ═══════════════════════════════════════════════════════════════════
# MARINAMATCH PIPELINE — MASTER PATCH RUNNER
# Run from workspace root: bash RUN_ALL_PATCHES.sh
# ═══════════════════════════════════════════════════════════════════

set -e
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PASS=0
FAIL=0

run_patch() {
  local name="$1"
  local script="$SCRIPT_DIR/$2"
  echo ""
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo "  $name"
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  if bash "$script"; then
    echo "  ✅ PASSED"
    ((PASS++))
  else
    echo "  ❌ FAILED — check output above"
    ((FAIL++))
  fi
}

echo "╔══════════════════════════════════════════════════════════════╗"
echo "║   MarinaMatch Pipeline — Full Enhancement Patcher           ║"
echo "║   10 patches · ~60 code changes · Salesforce/HubSpot parity ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""
echo "Working directory: $(pwd)"
echo "Node: $(node --version)"

# ── Phase A: Critical Bug Fixes ──────────────────────────────────────
run_patch "01 · Automation trigger on drag" "patch_01_automation_trigger.sh"
run_patch "02 · Automation execute actions" "patch_02_automation_execute.sh"
run_patch "03 · Deal card: activity badge + key dates + quick-log" "patch_03_deal_card.sh"
run_patch "04 · Quick-log modal + stage velocity header" "patch_04_quicklog_velocity.sh"
run_patch "05 · Activity Log ↔ Leads/Prospecting bridge" "patch_05_activity_leads_bridge.sh"

# ── Phase B: Feature Additions ───────────────────────────────────────
run_patch "06 · Stage gates + deal score badge + multi-condition automation" "patch_06_stage_gates_scoring.sh"
run_patch "07 · Activity count join in deals endpoint" "patch_07_deals_activity_join.sh"
run_patch "08 · In-app notifications + deal-rot scanner" "patch_08_notifications.sh"
run_patch "09 · Deal comparison in pipeline + velocity analytics tab" "patch_09_comparison_velocity.sh"
run_patch "10 · Deal health score + AI nudge sidebar + WIP limits" "patch_10_health_nudges_wip.sh"

echo ""
echo "════════════════════════════════════════════════"
echo "  RESULTS: ${PASS} passed · ${FAIL} failed"
echo "════════════════════════════════════════════════"

if [ $FAIL -gt 0 ]; then
  echo "⚠️  Some patches had issues. Review output above."
  echo "   Most failures are 'pattern not found' — these need manual edits."
fi

echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "  REQUIRED MANUAL STEPS (do these after running patches)"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "  1. DATABASE — run this SQL migration:"
echo "     cat /tmp/create_notifications_table.sql | psql \$DATABASE_URL"
echo ""
echo "  2. DATABASE — add columns to existing tables:"
echo "     ALTER TABLE crm_deals ADD COLUMN IF NOT EXISTS score INTEGER;"
echo "     ALTER TABLE crm_deals ADD COLUMN IF NOT EXISTS activity_count INTEGER DEFAULT 0;"
echo "     ALTER TABLE crm_pipeline_stages ADD COLUMN IF NOT EXISTS wip_limit INTEGER;"
echo "     ALTER TABLE crm_pipeline_stages ADD COLUMN IF NOT EXISTS required_fields JSONB DEFAULT '[]';"
echo "     ALTER TABLE crm_pipeline_automation_rules ADD COLUMN IF NOT EXISTS conditions JSONB DEFAULT '[]';"
echo ""
echo "  3. SCHEMA — add crmNotifications table to shared/schema.ts:"
echo "     export const crmNotifications = pgTable('crm_notifications', {"
echo "       id: varchar('id').primaryKey().default(sql\`gen_random_uuid()\`),"
echo "       orgId: varchar('org_id').notNull(),"
echo "       userId: varchar('user_id'),"
echo "       type: text('type').notNull().default('automation'),"
echo "       title: text('title').notNull(),"
echo "       body: text('body'),"
echo "       dealId: varchar('deal_id').references(() => crmDeals.id),"
echo "       metadata: jsonb('metadata').default({}),"
echo "       readAt: timestamp('read_at'),"
echo "       createdAt: timestamp('created_at').defaultNow(),"
echo "     });"
echo ""
echo "  4. SERVER ROUTES — register new routes in server/routes.ts:"
echo "     import notificationsRouter from './routes/notifications-routes';"
echo "     import dealHealthRouter from './routes/deal-health-routes';"
echo "     app.use('/api/notifications', notificationsRouter);"
echo "     app.use('/api/deal-health', dealHealthRouter);"
echo "     // Verify these are registered (they exist as files):"
echo "     app.use('/api/pipeline/automation', pipelineAutomationRoutes);"
echo "     app.use('/api/crm', crmPipelineEnhancementsRoutes);  // powers /enriched endpoint"
echo ""
echo "  5. TOPBAR — add NotificationBell to your header:"
echo "     import { NotificationBell } from '@/components/pipeline/NotificationBell';"
echo "     // Place <NotificationBell /> in your TopBar component"
echo ""
echo "  6. HEALTH SCORES — seed initial scores:"
echo "     # After deploying, call once:"
echo "     curl -X POST /api/deal-health/compute-all"
echo "     # Then add to a daily cron or on-login hook"
echo ""
echo "  7. VELOCITY TAB — import VelocityTabContent in PipelineInsights.tsx:"
echo "     import { VelocityTabContent } from '@/components/pipeline/VelocityTabContent';"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "  WHAT YOU GET AFTER ALL PATCHES"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "  KANBAN CARDS:"
echo "  ├── Activity count badge + last-contacted time"
echo "  ├── Next key date chip (DD / deposit / closing — color-coded)"
echo "  ├── Forecast category badge (Commit / Best Case / Omit)"
echo "  ├── Deal health score badge (0-100, green/yellow/red)"  
echo "  ├── Shift+click multi-select for comparison"
echo "  ├── Hover quick-log strip (call / email / note)"
echo "  └── Selection ring when comparison-selected"
echo ""
echo "  PIPELINE TOOLBAR:"
echo "  ├── Smart Nudges sidebar (stale deals + expiring deadlines)"
echo "  ├── Compare button (active when 2+ deals selected)"
echo "  └── Deal comparison grid with best-value highlighting"
echo ""
echo "  STAGE COLUMNS:"
echo "  ├── Avg days velocity stat (green/amber/red)"
echo "  └── WIP limit warning badge (when column is over limit)"
echo ""
echo "  AUTOMATION ENGINE:"
echo "  ├── Rules fire on every stage-change drag"
echo "  ├── 5 action types: create_task | send_notification | update_field | assign_owner | move_stage"
echo "  ├── Multi-condition support (AND logic, 6 field types)"
echo "  └── Stage entry gates (block drag if required fields missing)"
echo ""
echo "  ACTIVITY LOG:"
echo "  ├── Entity filter: All / Deals / Leads / Contacts / Companies"
echo "  ├── Lead links in activity cards"
echo "  └── lead origin in activity-association-service"
echo ""
echo "  LEADS / PROSPECTING:"
echo "  ├── Activity button on each lead card"
echo "  └── Activity feed association for leads → contacts/companies"
echo ""
echo "  NOTIFICATIONS:"
echo "  ├── In-app bell with unread count badge"
echo "  ├── Deal-rot scanner (auto-creates alerts for stale deals)"
echo "  └── Automation actions can push notifications"
echo ""
echo "  ANALYTICS:"
echo "  ├── Velocity tab: stage bar chart + bottleneck KPIs"
echo "  └── Deal comparison panel (inline + full-page)"
echo ""
