// Auto-generated by crm_patch_10x_records.sh
// Rich content tabs for Company Record: Portfolio, Intel, Models, Activities, Contacts, Deals

import { useQuery } from '@tanstack/react-query';
import { useState } from 'react';
import { useLocation } from 'wouter';
import { Badge } from '@/components/ui/badge';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Skeleton } from '@/components/ui/skeleton';
import { Progress } from '@/components/ui/progress';
import {
  Anchor, Building2, MapPin, DollarSign, TrendingUp, Activity,
  ExternalLink, ChevronRight, Phone, Mail, Clock, Calendar,
  FileText, BarChart3, Newspaper, Users, CheckCircle2, Circle,
  AlertCircle, MessageSquare, ArrowUpRight,
} from 'lucide-react';
import { format } from 'date-fns';
import { apiRequest } from '@/lib/queryClient';
import { cn } from '@/lib/utils';
import { BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer, PieChart, Pie, Cell } from 'recharts';

function fmtCurrency(v: string | number | null): string {
  if (!v) return '—';
  const n = typeof v === 'string' ? parseFloat(v) : v;
  if (isNaN(n)) return '—';
  if (n >= 1_000_000) return `$${(n / 1_000_000).toFixed(1)}M`;
  if (n >= 1_000) return `$${(n / 1_000).toFixed(0)}K`;
  return `$${n.toFixed(0)}`;
}
function fmtDate(d: string | null | undefined): string {
  if (!d) return '—';
  try { return format(new Date(d), 'MM/dd/yyyy'); } catch { return '—'; }
}
function fmtLabel(str: string): string {
  return str.split(/[_-]/).map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' ');
}
function EmptyState({ icon: Icon, title, subtitle, action }: { icon: any; title: string; subtitle?: string; action?: { label: string; href: string } }) {
  return (
    <div className="flex flex-col items-center justify-center py-16 text-center">
      <div className="rounded-full bg-gray-100 p-4 mb-4"><Icon className="h-8 w-8 text-gray-400" /></div>
      <p className="text-sm font-medium text-gray-600">{title}</p>
      {subtitle && <p className="text-xs text-gray-400 mt-1 max-w-xs">{subtitle}</p>}
      {action && (
        <a href={action.href} className="mt-4 inline-flex items-center gap-1.5 px-4 py-2 rounded-lg bg-blue-600 text-white text-xs font-medium hover:bg-blue-700 transition-colors">
          {action.label} →
        </a>
      )}
    </div>
  );
}

const listingStatusColors: Record<string, string> = {
  off_market: 'bg-gray-100 text-gray-700', on_market: 'bg-green-100 text-green-700',
  under_loi: 'bg-amber-100 text-amber-700', under_contract: 'bg-blue-100 text-blue-700',
  closed: 'bg-purple-100 text-purple-700', portfolio: 'bg-teal-100 text-teal-700',
  watchlist: 'bg-orange-100 text-orange-700', available: 'bg-green-100 text-green-700',
};
const CHART_COLORS = ['#3b82f6','#10b981','#8b5cf6','#f59e0b','#ef4444','#06b6d4'];
const activityTypeConfig: Record<string, { icon: any; color: string; bg: string }> = {
  call: { icon: Phone, color: 'text-blue-600', bg: 'bg-blue-50' },
  email: { icon: Mail, color: 'text-indigo-600', bg: 'bg-indigo-50' },
  meeting: { icon: Calendar, color: 'text-emerald-600', bg: 'bg-emerald-50' },
  note: { icon: MessageSquare, color: 'text-gray-600', bg: 'bg-gray-50' },
  follow_up: { icon: Clock, color: 'text-amber-600', bg: 'bg-amber-50' },
  task: { icon: FileText, color: 'text-purple-600', bg: 'bg-purple-50' },
  site_visit: { icon: MapPin, color: 'text-rose-600', bg: 'bg-rose-50' },
};
const dealStageColors: Record<string, string> = {
  prospecting: 'bg-gray-100 text-gray-700', qualification: 'bg-blue-100 text-blue-700',
  proposal: 'bg-indigo-100 text-indigo-700', negotiation: 'bg-amber-100 text-amber-700',
  closed_won: 'bg-emerald-100 text-emerald-700', 'closed-won': 'bg-emerald-100 text-emerald-700',
  closed_lost: 'bg-red-100 text-red-700', 'closed-lost': 'bg-red-100 text-red-700',
};

// ── Portfolio Tab ─────────────────────────────────────────────────────
export function CompanyPortfolioTab({ properties }: { properties: any[] }) {
  const [, setLocation] = useLocation();
  if (!properties?.length) return <EmptyState icon={Building2} title="No properties in portfolio" subtitle="Link properties to this company to build a portfolio view" />;
  const totalSlips = properties.reduce((s: number, p: any) => s + (p.wetSlips || 0), 0);
  const totalValue = properties.reduce((s: number, p: any) => s + (parseFloat(p.listingPrice || '0') || 0), 0);
  const onMarket = properties.filter((p: any) => ['on_market','available'].includes(p.listingStatus || p.status)).length;
  const statusGroups = properties.reduce((acc: any, p: any) => { const s = fmtLabel(p.listingStatus || p.status); acc[s] = (acc[s]||0)+1; return acc; }, {});
  const pieData = Object.entries(statusGroups).map(([name, value]) => ({ name, value }));
  return (
    <div className="space-y-4">
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
        <div className="rounded-xl bg-blue-50 p-3 text-center"><p className="text-xs text-blue-400">Properties</p><p className="text-2xl font-bold text-blue-700">{properties.length}</p></div>
        <div className="rounded-xl bg-teal-50 p-3 text-center"><p className="text-xs text-teal-400">Total Slips</p><p className="text-2xl font-bold text-teal-700">{totalSlips.toLocaleString()}</p></div>
        <div className="rounded-xl bg-emerald-50 p-3 text-center"><p className="text-xs text-emerald-400">On Market</p><p className="text-2xl font-bold text-emerald-700">{onMarket}</p></div>
        <div className="rounded-xl bg-purple-50 p-3 text-center"><p className="text-xs text-purple-400">Est. Value</p><p className="text-base font-bold text-purple-700">{fmtCurrency(totalValue)}</p></div>
      </div>
      {pieData.length > 1 && (
        <Card><CardHeader className="pb-1 pt-3 px-4"><CardTitle className="text-xs text-gray-500">Portfolio by Status</CardTitle></CardHeader>
          <CardContent className="px-2 pb-3">
            <ResponsiveContainer width="100%" height={120}>
              <PieChart><Pie data={pieData} dataKey="value" nameKey="name" cx="50%" cy="50%" outerRadius={50}>
                {pieData.map((_, i) => <Cell key={i} fill={CHART_COLORS[i % CHART_COLORS.length]} />)}
              </Pie><Tooltip /></PieChart>
            </ResponsiveContainer>
          </CardContent>
        </Card>
      )}
      <div className="grid grid-cols-1 gap-3">
        {properties.map((p: any) => {
          const status = p.listingStatus || p.status;
          const statusCls = listingStatusColors[status] || 'bg-gray-100 text-gray-700';
          return (
            <Card key={p.id} className="hover:shadow-md transition-all cursor-pointer group" onClick={() => setLocation(`/crm/properties/${p.id}`)}>
              <CardContent className="p-4">
                <div className="flex items-start justify-between gap-3">
                  <div className="flex items-center gap-3 min-w-0 flex-1">
                    <div className="rounded-xl bg-blue-50 p-2.5 shrink-0 group-hover:bg-blue-100 transition-colors"><Anchor className="h-5 w-5 text-blue-600" /></div>
                    <div className="min-w-0">
                      <p className="text-sm font-semibold text-gray-900 truncate group-hover:text-blue-600 transition-colors">{p.title}</p>
                      <p className="text-xs text-gray-500">{[p.city, p.state].filter(Boolean).join(', ') || '—'}</p>
                    </div>
                  </div>
                  <div className="flex items-center gap-2 shrink-0">
                    {p.listingPrice && <span className="text-sm font-bold text-gray-800">{fmtCurrency(p.listingPrice)}</span>}
                    <Badge className={`text-[10px] ${statusCls}`}>{fmtLabel(status)}</Badge>
                    <ChevronRight className="h-4 w-4 text-gray-300 group-hover:text-blue-500 transition-colors" />
                  </div>
                </div>
                <div className="flex items-center gap-4 mt-3 pt-3 border-t border-dashed text-xs text-gray-500">
                  <span className="flex items-center gap-1"><Anchor className="h-3 w-3 text-blue-400" /><span className="font-medium text-gray-700">{p.wetSlips ?? '—'}</span> wet</span>
                  {p.annualRevenue && <span className="flex items-center gap-1"><DollarSign className="h-3 w-3 text-emerald-400" /><span className="font-medium text-gray-700">{fmtCurrency(p.annualRevenue)}</span>/yr</span>}
                  <span className="ml-auto text-gray-400">{fmtLabel(p.type)}</span>
                  {p.relationship && <Badge variant="outline" className="text-[10px]">{fmtLabel(p.relationship)}</Badge>}
                </div>
              </CardContent>
            </Card>
          );
        })}
      </div>
    </div>
  );
}

// ── Intel Tab ─────────────────────────────────────────────────────────
export function CompanyIntelTab({ state }: { state?: string | null }) {
  const { data, isLoading } = useQuery<any>({
    queryKey: ['docket-articles-company', state],
    queryFn: async () => {
      const params = new URLSearchParams({ limit: '15', status: 'approved' });
      if (state) params.set('state', state);
      const res = await apiRequest('GET', `/api/docket/articles?${params}`);
      return res.json();
    },
  });
  const articles: any[] = Array.isArray(data) ? data : data?.articles || [];
  const sentimentCounts = articles.reduce((acc: any, a: any) => { if (a.sentiment) acc[a.sentiment] = (acc[a.sentiment]||0)+1; return acc; }, {});
  if (isLoading) return <div className="space-y-3">{[...Array(4)].map((_, i) => <Card key={i}><CardContent className="p-4"><Skeleton className="h-16 w-full" /></CardContent></Card>)}</div>;
  if (!articles.length) return <EmptyState icon={Newspaper} title="No market intel" subtitle={state ? `No recent news for ${state}` : 'No market news available'} />;
  return (
    <div className="space-y-4">
      {Object.keys(sentimentCounts).length > 0 && (
        <Card><CardContent className="p-3">
          <p className="text-xs font-medium text-gray-600 mb-2">Market Sentiment ({articles.length} articles)</p>
          <div className="flex gap-2">
            {Object.entries(sentimentCounts).map(([s, count]: any) => (
              <div key={s} className={cn('flex-1 rounded-lg p-2 text-center', s==='positive'?'bg-green-100 text-green-700':s==='negative'?'bg-red-100 text-red-700':'bg-gray-100 text-gray-600')}>
                <p className="text-lg font-bold">{count}</p>
                <p className="text-[10px] capitalize">{s}</p>
              </div>
            ))}
          </div>
        </CardContent></Card>
      )}
      <div className="space-y-3">
        {articles.map((a: any) => {
          const sentCls = a.sentiment==='positive'?'bg-green-100 text-green-700':a.sentiment==='negative'?'bg-red-100 text-red-700':'bg-gray-100 text-gray-600';
          return (
            <Card key={a.id} className="hover:shadow-md transition-shadow">
              <CardContent className="p-4">
                <div className="flex items-start gap-3">
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-2 mb-1 flex-wrap">
                      {a.sentiment && <Badge className={`text-[10px] ${sentCls}`}>{a.sentiment}</Badge>}
                      {a.category && <Badge variant="outline" className="text-[10px]">{fmtLabel(a.category)}</Badge>}
                    </div>
                    <a href={a.url} target="_blank" rel="noopener noreferrer" className="text-sm font-semibold text-gray-900 hover:text-blue-600 line-clamp-2 transition-colors">{a.title}</a>
                    {a.summary && <p className="text-xs text-gray-500 mt-1 line-clamp-2">{a.summary}</p>}
                    <div className="flex items-center gap-3 mt-2 text-[10px] text-gray-400">
                      {a.source && <span className="font-medium">{a.source}</span>}
                      <span>{fmtDate(a.publishedAt)}</span>
                    </div>
                  </div>
                  <a href={a.url} target="_blank" rel="noopener noreferrer" className="p-1.5 rounded hover:bg-gray-100 shrink-0"><ExternalLink className="h-3.5 w-3.5 text-gray-400" /></a>
                </div>
              </CardContent>
            </Card>
          );
        })}
      </div>
    </div>
  );
}

// ── Models Tab ────────────────────────────────────────────────────────
export function CompanyModelsTab({ dealIds, propertyIds }: { dealIds?: string[]; propertyIds?: string[] }) {
  const [, setLocation] = useLocation();
  const { data: allProjects = [], isLoading } = useQuery<any[]>({
    queryKey: ['modeling-projects-company', dealIds?.join(','), propertyIds?.join(',')],
    queryFn: async () => {
      const res = await apiRequest('GET', '/api/modeling/projects');
      const all = await res.json();
      if (!dealIds?.length && !propertyIds?.length) return [];
      return (Array.isArray(all) ? all : []).filter((p: any) => dealIds?.includes(p.dealId) || propertyIds?.includes(p.propertyId));
    },
  });
  if (isLoading) return <div className="space-y-3">{[...Array(2)].map((_, i) => <Card key={i}><CardContent className="p-4"><Skeleton className="h-24 w-full" /></CardContent></Card>)}</div>;
  if (!allProjects.length) return <EmptyState icon={BarChart3} title="No financial models" subtitle="Models linked to this company's deals and properties will appear here" />;
  const chartData = allProjects.filter((p:any) => p.projectedIrr != null).map((p:any) => ({ name: p.name.substring(0,18), irr: parseFloat((p.projectedIrr*100).toFixed(1)) }));
  return (
    <div className="space-y-4">
      {chartData.length > 1 && (
        <Card><CardHeader className="pb-2 pt-3 px-4"><CardTitle className="text-sm">IRR Comparison</CardTitle></CardHeader>
          <CardContent className="px-2 pb-3">
            <ResponsiveContainer width="100%" height={120}>
              <BarChart data={chartData} barSize={28} layout="vertical">
                <XAxis type="number" tick={{ fontSize: 10 }} tickFormatter={(v:number) => `${v}%`} /><YAxis dataKey="name" type="category" tick={{ fontSize: 9 }} width={90} /><Tooltip formatter={(v:any) => `${v}%`} /><Bar dataKey="irr" fill="#8b5cf6" radius={[0,4,4,0]} />
              </BarChart>
            </ResponsiveContainer>
          </CardContent>
        </Card>
      )}
      {allProjects.map((proj: any) => {
        const statusCls = proj.status==='active'?'bg-green-100 text-green-700':proj.status==='archived'?'bg-red-100 text-red-700':'bg-gray-100 text-gray-600';
        return (
          <Card key={proj.id} className="hover:shadow-md transition-shadow cursor-pointer" onClick={() => setLocation(`/modeling/projects/${proj.id}/workspace`)}>
            <CardContent className="p-4">
              <div className="flex items-center justify-between mb-3">
                <div><p className="text-sm font-semibold text-gray-900">{proj.name}</p><div className="flex items-center gap-2 mt-0.5"><Badge className={`text-[10px] ${statusCls}`}>{proj.status||'draft'}</Badge>{proj.assetClass && <span className="text-[10px] text-gray-400">{fmtLabel(proj.assetClass)}</span>}</div></div>
                <ArrowUpRight className="h-4 w-4 text-gray-400" />
              </div>
              <div className="grid grid-cols-2 sm:grid-cols-4 gap-2">
                {proj.purchasePrice != null && <div className="rounded-lg bg-gray-50 p-2 text-center"><p className="text-[10px] text-gray-400">Price</p><p className="text-xs font-bold text-gray-700">{fmtCurrency(proj.purchasePrice)}</p></div>}
                {proj.goingInCapRate != null && <div className="rounded-lg bg-blue-50 p-2 text-center"><p className="text-[10px] text-blue-400">Cap Rate</p><p className="text-xs font-bold text-blue-700">{(proj.goingInCapRate*100).toFixed(2)}%</p></div>}
                {proj.projectedIrr != null && <div className="rounded-lg bg-emerald-50 p-2 text-center"><p className="text-[10px] text-emerald-400">IRR</p><p className="text-xs font-bold text-emerald-700">{(proj.projectedIrr*100).toFixed(1)}%</p></div>}
                {proj.equityMultiple != null && <div className="rounded-lg bg-purple-50 p-2 text-center"><p className="text-[10px] text-purple-400">EM</p><p className="text-xs font-bold text-purple-700">{proj.equityMultiple.toFixed(2)}x</p></div>}
              </div>
            </CardContent>
          </Card>
        );
      })}
    </div>
  );
}

// ── Activities Tab ────────────────────────────────────────────────────
export function CompanyActivitiesTab({ companyId }: { companyId: string }) {
  const [filter, setFilter] = useState<'all' | 'open' | 'done'>('all');
  const { data, isLoading } = useQuery<any[]>({
    queryKey: ['company-activities-full', companyId, filter],
    queryFn: async () => {
      const params = new URLSearchParams({ entityType: 'company', entityId: companyId, limit: '50' });
      if (filter !== 'all') params.set('status', filter);
      const res = await apiRequest('GET', `/api/crm/activities?${params}`);
      const arr = await res.json();
      return Array.isArray(arr) ? arr : arr.activities || [];
    },
  });
  const activities = data || [];
  const typeCounts = activities.reduce((acc: any, a: any) => { acc[a.type] = (acc[a.type]||0)+1; return acc; }, {});
  const typeChartData = Object.entries(typeCounts).map(([name, value]) => ({ name: fmtLabel(name), value }));
  return (
    <div className="space-y-3">
      <div className="flex items-center justify-between">
        <div className="flex gap-2">
          {(['all','open','done'] as const).map(f => (
            <button key={f} onClick={() => setFilter(f)} className={cn('text-xs px-3 py-1.5 rounded-full border transition-colors', filter===f?'bg-blue-600 text-white border-blue-600':'bg-white text-gray-600 border-gray-200 hover:bg-gray-50')}>
              {f.charAt(0).toUpperCase()+f.slice(1)}
            </button>
          ))}
        </div>
        <span className="text-xs text-gray-400">{activities.length} total</span>
      </div>
      {typeChartData.length > 1 && filter==='all' && (
        <Card><CardContent className="px-2 py-3">
          <ResponsiveContainer width="100%" height={70}>
            <BarChart data={typeChartData} barSize={18}><XAxis dataKey="name" tick={{ fontSize: 9 }} axisLine={false} tickLine={false} /><YAxis hide /><Tooltip /><Bar dataKey="value" fill="#6366f1" radius={[3,3,0,0]} /></BarChart>
          </ResponsiveContainer>
        </CardContent></Card>
      )}
      {isLoading && <div className="space-y-2">{[...Array(4)].map((_, i) => <Card key={i}><CardContent className="p-3"><Skeleton className="h-10 w-full" /></CardContent></Card>)}</div>}
      {!isLoading && !activities.length && <EmptyState icon={Activity} title="No activities yet" subtitle="Log a call, email, or meeting to track engagement" />}
      {activities.map((act: any) => {
        const cfg = activityTypeConfig[act.type] || activityTypeConfig.note;
        const Icon = cfg.icon;
        const isDone = act.status==='completed';
        const isOverdue = !isDone && act.scheduledAt && new Date(act.scheduledAt) < new Date();
        return (
          <Card key={act.id} className={cn(isDone && 'opacity-60')}>
            <CardContent className="p-3">
              <div className="flex items-start gap-3">
                <div className={cn('rounded-lg p-2 shrink-0', cfg.bg)}><Icon className={cn('h-3.5 w-3.5', cfg.color)} /></div>
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-2">
                    <p className="text-sm font-medium text-gray-900 truncate">{act.subject}</p>
                    {isDone?<CheckCircle2 className="h-3.5 w-3.5 text-emerald-500 shrink-0" />:isOverdue?<AlertCircle className="h-3.5 w-3.5 text-red-500 shrink-0" />:<Circle className="h-3.5 w-3.5 text-gray-300 shrink-0" />}
                  </div>
                  <div className="flex items-center gap-3 mt-0.5 text-[10px] text-gray-400">
                    <span className="capitalize">{act.type?.replace(/_/g,' ')}</span>
                    {act.scheduledAt && <span className={isOverdue?'text-red-500 font-medium':''}>{fmtDate(act.scheduledAt)}</span>}
                    {act.completedAt && <span className="text-emerald-500">Done {fmtDate(act.completedAt)}</span>}
                  </div>
                  {act.notes && <p className="text-xs text-gray-500 mt-1 line-clamp-1">{act.notes}</p>}
                </div>
              </div>
            </CardContent>
          </Card>
        );
      })}
    </div>
  );
}

// ── Enhanced Contacts Tab ─────────────────────────────────────────────
export function CompanyContactsTabEnhanced({ contacts }: { contacts: any[] }) {
  const [, setLocation] = useLocation();
  const [search, setSearch] = useState('');
  if (!contacts?.length) return <EmptyState icon={Users} title="No contacts linked" subtitle="Add contacts to this company to see them here" />;
  const primary = contacts.find((c:any) => c.isPrimary);
  const filtered = contacts.filter((c:any) => search==='' || `${c.firstName} ${c.lastName} ${c.email}`.toLowerCase().includes(search.toLowerCase()));
  const tagColors: Record<string,string> = { lead:'bg-blue-100 text-blue-700',seller:'bg-purple-100 text-purple-700',broker:'bg-emerald-100 text-emerald-700',lender:'bg-cyan-100 text-cyan-700',investor:'bg-indigo-100 text-indigo-700',other:'bg-gray-100 text-gray-600' };
  return (
    <div className="space-y-3">
      {primary && (
        <Card className="border-blue-200 bg-blue-50/50 cursor-pointer hover:shadow-md" onClick={() => setLocation(`/crm/contacts/${primary.id}`)}>
          <CardContent className="p-4">
            <div className="flex items-center gap-3">
              <div className="rounded-full bg-blue-100 h-10 w-10 flex items-center justify-center shrink-0 text-sm font-bold text-blue-700">{primary.firstName[0]}{primary.lastName[0]}</div>
              <div className="flex-1 min-w-0">
                <div className="flex items-center gap-2"><p className="text-sm font-semibold text-gray-900">{primary.firstName} {primary.lastName}</p><Badge className="text-[10px] bg-blue-600 text-white">Primary</Badge></div>
                <p className="text-xs text-gray-500">{primary.position || primary.role || '—'} · {primary.email}</p>
              </div>
              <ChevronRight className="h-4 w-4 text-blue-400 shrink-0" />
            </div>
          </CardContent>
        </Card>
      )}
      {contacts.length > 5 && <input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search contacts..." className="w-full h-8 text-xs border rounded-lg px-3 bg-white focus:outline-none focus:ring-1 focus:ring-blue-500" />}
      <div className="space-y-2">
        {filtered.filter((c:any) => !c.isPrimary).map((contact: any) => (
          <Card key={contact.id} className="hover:shadow-sm transition-shadow cursor-pointer" onClick={() => setLocation(`/crm/contacts/${contact.id}`)}>
            <CardContent className="p-3">
              <div className="flex items-center gap-3">
                <div className="rounded-full bg-gray-100 h-8 w-8 flex items-center justify-center shrink-0 text-xs font-bold text-gray-600">{contact.firstName[0]}{contact.lastName[0]}</div>
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-2">
                    <p className="text-sm font-medium text-gray-900 truncate">{contact.firstName} {contact.lastName}</p>
                    {contact.contactTag && <Badge className={`text-[10px] ${tagColors[contact.contactTag]||tagColors.other}`}>{fmtLabel(contact.contactTag)}</Badge>}
                  </div>
                  <p className="text-xs text-gray-500 truncate">{contact.position||contact.role||'—'} · {contact.email}</p>
                </div>
                <ChevronRight className="h-4 w-4 text-gray-300 shrink-0" />
              </div>
            </CardContent>
          </Card>
        ))}
      </div>
    </div>
  );
}

// ── Enhanced Deals Tab ────────────────────────────────────────────────
export function CompanyDealsTabEnhanced({ deals }: { deals: any[] }) {
  const [, setLocation] = useLocation();
  if (!deals?.length) return <EmptyState icon={DollarSign} title="No deals yet" subtitle="Deals linked to this company will appear here" />;
  const totalPipeline = deals.reduce((s:number,d:any) => s+(parseFloat(d.value||'0')||0), 0);
  const openDeals = deals.filter((d:any) => !d.stage.includes('closed'));
  const stageData = Object.entries(deals.reduce((acc:any,d:any) => { const s=fmtLabel(d.stage); acc[s]=(acc[s]||0)+(parseFloat(d.value||'0')||0); return acc; }, {})).map(([name,value]) => ({name,value}));
  return (
    <div className="space-y-4">
      <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
        <div className="rounded-xl bg-blue-50 p-3 text-center"><p className="text-xs text-blue-400">Total</p><p className="text-2xl font-bold text-blue-700">{deals.length}</p></div>
        <div className="rounded-xl bg-emerald-50 p-3 text-center"><p className="text-xs text-emerald-400">Open</p><p className="text-2xl font-bold text-emerald-700">{openDeals.length}</p></div>
        <div className="rounded-xl bg-purple-50 p-3 text-center"><p className="text-xs text-purple-400">Pipeline</p><p className="text-base font-bold text-purple-700">{fmtCurrency(totalPipeline)}</p></div>
      </div>
      {stageData.length > 1 && <Card><CardContent className="px-2 pt-3 pb-2"><ResponsiveContainer width="100%" height={90}><BarChart data={stageData} barSize={24}><XAxis dataKey="name" tick={{fontSize:9}} axisLine={false} tickLine={false}/><YAxis hide/><Tooltip formatter={(v:number)=>fmtCurrency(v)}/><Bar dataKey="value" fill="#3b82f6" radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></CardContent></Card>}
      <div className="space-y-2">
        {deals.map((deal:any) => {
          const stageCls = dealStageColors[deal.stage]||'bg-gray-100 text-gray-700';
          const isClosed = deal.stage.includes('closed');
          return (
            <Card key={deal.id} className={cn('hover:shadow-md cursor-pointer',isClosed&&'opacity-60')} onClick={()=>setLocation(`/crm/deals/${deal.id}`)}>
              <CardContent className="p-4">
                <div className="flex items-center justify-between">
                  <div className="min-w-0 flex-1">
                    <div className="flex items-center gap-2"><p className="text-sm font-semibold text-gray-900 truncate">{deal.name}</p><Badge className={`text-[10px] shrink-0 ${stageCls}`}>{fmtLabel(deal.stage)}</Badge></div>
                    <div className="flex items-center gap-4 mt-1 text-xs text-gray-500">
                      {deal.value && <span className="font-medium text-gray-700">{fmtCurrency(deal.value)}</span>}
                      {deal.probability!=null && <span>{deal.probability}%</span>}
                      {deal.expectedCloseDate && <span>Close: {fmtDate(deal.expectedCloseDate)}</span>}
                    </div>
                    {deal.probability!=null && !isClosed && <Progress value={deal.probability} className="h-1 mt-2"/>}
                  </div>
                  <ChevronRight className="h-4 w-4 text-gray-400 shrink-0 ml-3"/>
                </div>
              </CardContent>
            </Card>
          );
        })}
      </div>
    </div>
  );
}
