// Auto-generated by crm_patch_10x_records.sh
// Rich content tabs for Contact Record: Properties, Market Intel, Financial Models, Activities, Deals

import { useQuery } from '@tanstack/react-query';
import { useState } from 'react';
import { useLocation } from 'wouter';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Skeleton } from '@/components/ui/skeleton';
import { Progress } from '@/components/ui/progress';
import {
  MapPin, Building2, DollarSign, TrendingUp, Activity, Clock,
  ExternalLink, ChevronRight, Anchor, Phone, Mail, FileText,
  BarChart3, Newspaper, Calendar, Target, ArrowUpRight,
  CheckCircle2, Circle, AlertCircle, MessageSquare,
} from 'lucide-react';
import { format } from 'date-fns';
import { apiRequest } from '@/lib/queryClient';
import { cn, formatCurrency } from '@/lib/utils';
import { BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer } from 'recharts';

function fmtCurrency(v: string | number | null): string {
  if (!v) return '—';
  const n = typeof v === 'string' ? parseFloat(v) : v;
  if (isNaN(n)) return '—';
  if (n >= 1_000_000) return `$${(n / 1_000_000).toFixed(1)}M`;
  if (n >= 1_000) return `$${(n / 1_000).toFixed(0)}K`;
  return `$${n.toFixed(0)}`;
}
function fmtDate(d: string | null | undefined): string {
  if (!d) return '—';
  try { return format(new Date(d), 'MM/dd/yyyy'); } catch { return '—'; }
}
function fmtLabel(str: string): string {
  return str.split(/[_-]/).map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' ');
}

function EmptyState({ icon: Icon, title, subtitle }: { icon: any; title: string; subtitle?: string }) {
  return (
    <div className="flex flex-col items-center justify-center py-16 text-center">
      <div className="rounded-full bg-gray-100 p-4 mb-4"><Icon className="h-8 w-8 text-gray-400" /></div>
      <p className="text-sm font-medium text-gray-600">{title}</p>
      {subtitle && <p className="text-xs text-gray-400 mt-1 max-w-xs">{subtitle}</p>}
    </div>
  );
}

const listingStatusColors: Record<string, string> = {
  off_market: 'bg-gray-100 text-gray-700', on_market: 'bg-green-100 text-green-700',
  under_loi: 'bg-amber-100 text-amber-700', under_contract: 'bg-blue-100 text-blue-700',
  closed: 'bg-purple-100 text-purple-700', portfolio: 'bg-teal-100 text-teal-700',
  watchlist: 'bg-orange-100 text-orange-700', available: 'bg-green-100 text-green-700',
};

const activityTypeConfig: Record<string, { icon: any; color: string; bg: string }> = {
  call:       { icon: Phone,         color: 'text-blue-600',    bg: 'bg-blue-50' },
  email:      { icon: Mail,          color: 'text-indigo-600',  bg: 'bg-indigo-50' },
  meeting:    { icon: Calendar,      color: 'text-emerald-600', bg: 'bg-emerald-50' },
  note:       { icon: MessageSquare, color: 'text-gray-600',    bg: 'bg-gray-50' },
  follow_up:  { icon: Clock,         color: 'text-amber-600',   bg: 'bg-amber-50' },
  task:       { icon: FileText,      color: 'text-purple-600',  bg: 'bg-purple-50' },
  site_visit: { icon: MapPin,        color: 'text-rose-600',    bg: 'bg-rose-50' },
};

const dealStageColors: Record<string, string> = {
  prospecting: 'bg-gray-100 text-gray-700', qualification: 'bg-blue-100 text-blue-700',
  proposal: 'bg-indigo-100 text-indigo-700', negotiation: 'bg-amber-100 text-amber-700',
  closed_won: 'bg-emerald-100 text-emerald-700', 'closed-won': 'bg-emerald-100 text-emerald-700',
  closed_lost: 'bg-red-100 text-red-700', 'closed-lost': 'bg-red-100 text-red-700',
};

// ── Properties Tab ────────────────────────────────────────────────────
export function ContactPropertiesTab({ properties }: { properties: any[] }) {
  const [, setLocation] = useLocation();
  if (!properties?.length) return <EmptyState icon={Building2} title="No properties linked" subtitle="Link properties to this contact to see them here" />;
  return (
    <div className="grid grid-cols-1 gap-3">
      {properties.map((p: any) => {
        const status = p.listingStatus || p.status;
        const statusCls = listingStatusColors[status] || 'bg-gray-100 text-gray-700';
        return (
          <Card key={p.id} className="hover:shadow-md transition-all cursor-pointer border-l-4 border-l-transparent hover:border-l-blue-400" onClick={() => setLocation(`/crm/properties/${p.id}`)}>
            <CardContent className="p-4">
              <div className="flex items-start justify-between gap-3">
                <div className="flex items-center gap-3 min-w-0">
                  <div className="rounded-lg bg-blue-50 p-2 shrink-0"><Anchor className="h-4 w-4 text-blue-600" /></div>
                  <div className="min-w-0">
                    <p className="text-sm font-semibold text-gray-900 truncate">{p.title}</p>
                    <p className="text-xs text-gray-500 mt-0.5">{[p.city, p.state].filter(Boolean).join(', ') || '—'}</p>
                  </div>
                </div>
                <div className="flex items-center gap-2 shrink-0">
                  {p.listingPrice && <span className="text-sm font-semibold text-gray-800">{fmtCurrency(p.listingPrice)}</span>}
                  <Badge className={`text-[10px] ${statusCls}`}>{fmtLabel(status)}</Badge>
                  <ChevronRight className="h-4 w-4 text-gray-400" />
                </div>
              </div>
              <div className="flex items-center gap-4 mt-3 pt-3 border-t text-xs text-gray-500">
                <span className="flex items-center gap-1"><Anchor className="h-3 w-3" />{p.wetSlips ?? '—'} wet slips</span>
                <span className="flex items-center gap-1"><Building2 className="h-3 w-3" />{fmtLabel(p.type)}</span>
                {p.relationship && <Badge variant="outline" className="text-[10px] ml-auto">{fmtLabel(p.relationship)}</Badge>}
              </div>
            </CardContent>
          </Card>
        );
      })}
    </div>
  );
}

// ── Intel Tab ─────────────────────────────────────────────────────────
export function ContactIntelTab({ state }: { state?: string | null }) {
  const { data, isLoading } = useQuery<any>({
    queryKey: ['docket-articles-contact', state],
    queryFn: async () => {
      const params = new URLSearchParams({ limit: '12', status: 'approved' });
      if (state) params.set('state', state);
      const res = await apiRequest('GET', `/api/docket/articles?${params}`);
      return res.json();
    },
  });
  const articles: any[] = Array.isArray(data) ? data : data?.articles || [];
  if (isLoading) return <div className="space-y-3">{[...Array(4)].map((_, i) => <Card key={i}><CardContent className="p-4"><Skeleton className="h-16 w-full" /></CardContent></Card>)}</div>;
  if (!articles.length) return <EmptyState icon={Newspaper} title="No market intel available" subtitle="DockTalk news relevant to this contact's geography will appear here" />;
  return (
    <div className="space-y-3">
      {articles.map((a: any) => {
        const sentCls = a.sentiment === 'positive' ? 'bg-green-100 text-green-700' : a.sentiment === 'negative' ? 'bg-red-100 text-red-700' : 'bg-gray-100 text-gray-600';
        return (
          <Card key={a.id} className="hover:shadow-md transition-shadow">
            <CardContent className="p-4">
              <div className="flex items-start gap-3">
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-2 mb-1 flex-wrap">
                    {a.sentiment && <Badge className={`text-[10px] ${sentCls}`}>{a.sentiment}</Badge>}
                    {a.category && <Badge variant="outline" className="text-[10px]">{fmtLabel(a.category)}</Badge>}
                  </div>
                  <a href={a.url} target="_blank" rel="noopener noreferrer" className="text-sm font-semibold text-gray-900 hover:text-blue-600 line-clamp-2 transition-colors">{a.title}</a>
                  {a.summary && <p className="text-xs text-gray-500 mt-1 line-clamp-2">{a.summary}</p>}
                  <div className="flex items-center gap-3 mt-2 text-[10px] text-gray-400">
                    {a.source && <span>{a.source}</span>}
                    <span>{fmtDate(a.publishedAt)}</span>
                  </div>
                </div>
                <a href={a.url} target="_blank" rel="noopener noreferrer" className="p-1.5 rounded hover:bg-gray-100 shrink-0"><ExternalLink className="h-3.5 w-3.5 text-gray-400" /></a>
              </div>
            </CardContent>
          </Card>
        );
      })}
    </div>
  );
}

// ── Models Tab ────────────────────────────────────────────────────────
export function ContactModelsTab({ dealIds }: { dealIds?: string[] }) {
  const [, setLocation] = useLocation();
  const { data: allProjects = [], isLoading } = useQuery<any[]>({
    queryKey: ['modeling-projects-contact', dealIds?.join(',')],
    queryFn: async () => {
      const res = await apiRequest('GET', '/api/modeling/projects');
      const all = await res.json();
      if (!dealIds?.length) return [];
      return (Array.isArray(all) ? all : []).filter((p: any) => dealIds.includes(p.dealId));
    },
  });
  if (isLoading) return <div className="space-y-3">{[...Array(2)].map((_, i) => <Card key={i}><CardContent className="p-4"><Skeleton className="h-20 w-full" /></CardContent></Card>)}</div>;
  if (!allProjects.length) return <EmptyState icon={BarChart3} title="No financial models linked" subtitle="Models linked to this contact's deals will appear here" />;
  return (
    <div className="space-y-3">
      {allProjects.map((proj: any) => {
        const statusCls = proj.status === 'active' ? 'bg-green-100 text-green-700' : proj.status === 'archived' ? 'bg-red-100 text-red-700' : 'bg-gray-100 text-gray-600';
        return (
          <Card key={proj.id} className="hover:shadow-md transition-shadow cursor-pointer" onClick={() => setLocation(`/modeling/projects/${proj.id}/workspace`)}>
            <CardContent className="p-4">
              <div className="flex items-center justify-between mb-3">
                <div>
                  <p className="text-sm font-semibold text-gray-900">{proj.name}</p>
                  <p className="text-xs text-gray-400 mt-0.5">{fmtDate(proj.createdAt)}</p>
                </div>
                <div className="flex items-center gap-2">
                  <Badge className={`text-[10px] ${statusCls}`}>{proj.status || 'draft'}</Badge>
                  <ArrowUpRight className="h-4 w-4 text-gray-400" />
                </div>
              </div>
              <div className="grid grid-cols-2 sm:grid-cols-3 gap-2">
                {proj.goingInCapRate != null && <div className="rounded-lg bg-blue-50 p-2 text-center"><p className="text-[10px] text-blue-400">Cap Rate</p><p className="text-xs font-bold text-blue-700">{(proj.goingInCapRate * 100).toFixed(2)}%</p></div>}
                {proj.projectedIrr != null && <div className="rounded-lg bg-emerald-50 p-2 text-center"><p className="text-[10px] text-emerald-400">IRR</p><p className="text-xs font-bold text-emerald-700">{(proj.projectedIrr * 100).toFixed(1)}%</p></div>}
                {proj.equityMultiple != null && <div className="rounded-lg bg-purple-50 p-2 text-center"><p className="text-[10px] text-purple-400">EM</p><p className="text-xs font-bold text-purple-700">{proj.equityMultiple.toFixed(2)}x</p></div>}
              </div>
            </CardContent>
          </Card>
        );
      })}
    </div>
  );
}

// ── Activities Tab ────────────────────────────────────────────────────
export function ContactActivitiesTab({ contactId }: { contactId: string }) {
  const [filter, setFilter] = useState<'all' | 'open' | 'done'>('all');
  const { data, isLoading } = useQuery<any[]>({
    queryKey: ['contact-activities-full', contactId, filter],
    queryFn: async () => {
      const params = new URLSearchParams({ entityType: 'contact', entityId: contactId, limit: '50' });
      if (filter !== 'all') params.set('status', filter);
      const res = await apiRequest('GET', `/api/crm/activities?${params}`);
      const arr = await res.json();
      return Array.isArray(arr) ? arr : arr.activities || [];
    },
  });
  const activities = data || [];
  return (
    <div className="space-y-3">
      <div className="flex gap-2">
        {(['all', 'open', 'done'] as const).map(f => (
          <button key={f} onClick={() => setFilter(f)} className={cn('text-xs px-3 py-1.5 rounded-full border transition-colors', filter === f ? 'bg-blue-600 text-white border-blue-600' : 'bg-white text-gray-600 border-gray-200 hover:bg-gray-50')}>
            {f.charAt(0).toUpperCase() + f.slice(1)}
          </button>
        ))}
        <span className="ml-auto text-xs text-gray-400 self-center">{activities.length} total</span>
      </div>
      {isLoading && <div className="space-y-2">{[...Array(4)].map((_, i) => <Card key={i}><CardContent className="p-3"><Skeleton className="h-10 w-full" /></CardContent></Card>)}</div>}
      {!isLoading && !activities.length && <EmptyState icon={Activity} title="No activities yet" subtitle="Log a call, email, or meeting to start the activity history" />}
      {activities.map((act: any) => {
        const cfg = activityTypeConfig[act.type] || activityTypeConfig.note;
        const Icon = cfg.icon;
        const isDone = act.status === 'completed';
        const isOverdue = !isDone && act.scheduledAt && new Date(act.scheduledAt) < new Date();
        return (
          <Card key={act.id} className={cn(isDone && 'opacity-60')}>
            <CardContent className="p-3">
              <div className="flex items-start gap-3">
                <div className={cn('rounded-lg p-2 shrink-0', cfg.bg)}><Icon className={cn('h-3.5 w-3.5', cfg.color)} /></div>
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-2">
                    <p className="text-sm font-medium text-gray-900 truncate">{act.subject}</p>
                    {isDone ? <CheckCircle2 className="h-3.5 w-3.5 text-emerald-500 shrink-0" /> : isOverdue ? <AlertCircle className="h-3.5 w-3.5 text-red-500 shrink-0" /> : <Circle className="h-3.5 w-3.5 text-gray-300 shrink-0" />}
                  </div>
                  <div className="flex items-center gap-3 mt-0.5 text-[10px] text-gray-400">
                    <span className="capitalize">{act.type?.replace(/_/g, ' ')}</span>
                    {act.scheduledAt && <span className={isOverdue ? 'text-red-500 font-medium' : ''}>{fmtDate(act.scheduledAt)}</span>}
                    {act.completedAt && <span className="text-emerald-500">Done {fmtDate(act.completedAt)}</span>}
                  </div>
                  {act.notes && <p className="text-xs text-gray-500 mt-1 line-clamp-1">{act.notes}</p>}
                </div>
              </div>
            </CardContent>
          </Card>
        );
      })}
    </div>
  );
}

// ── Enhanced Deals Tab ────────────────────────────────────────────────
export function ContactDealsTabEnhanced({ deals }: { deals: any[] }) {
  const [, setLocation] = useLocation();
  if (!deals?.length) return <EmptyState icon={DollarSign} title="No deals yet" subtitle="Deals linked to this contact will appear here" />;
  const totalPipeline = deals.reduce((s: number, d: any) => s + (parseFloat(d.value || '0') || 0), 0);
  const openDeals = deals.filter((d: any) => !d.stage.includes('closed'));
  const chartData = Object.entries(deals.reduce((acc: any, d: any) => { const s = fmtLabel(d.stage); acc[s] = (acc[s] || 0) + (parseFloat(d.value || '0') || 0); return acc; }, {})).map(([name, value]) => ({ name, value }));
  return (
    <div className="space-y-4">
      <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
        <div className="rounded-xl bg-blue-50 p-3 text-center"><p className="text-xs text-blue-400">Total</p><p className="text-2xl font-bold text-blue-700">{deals.length}</p></div>
        <div className="rounded-xl bg-emerald-50 p-3 text-center"><p className="text-xs text-emerald-400">Open</p><p className="text-2xl font-bold text-emerald-700">{openDeals.length}</p></div>
        <div className="rounded-xl bg-purple-50 p-3 text-center"><p className="text-xs text-purple-400">Pipeline</p><p className="text-lg font-bold text-purple-700">{fmtCurrency(totalPipeline)}</p></div>
      </div>
      {chartData.length > 1 && (
        <Card><CardContent className="px-2 pt-3 pb-2">
          <ResponsiveContainer width="100%" height={100}>
            <BarChart data={chartData} barSize={24}><XAxis dataKey="name" tick={{ fontSize: 9 }} axisLine={false} tickLine={false} /><YAxis hide /><Tooltip formatter={(v: number) => fmtCurrency(v)} /><Bar dataKey="value" fill="#3b82f6" radius={[4, 4, 0, 0]} /></BarChart>
          </ResponsiveContainer>
        </CardContent></Card>
      )}
      <div className="space-y-2">
        {deals.map((deal: any) => {
          const stageCls = dealStageColors[deal.stage] || 'bg-gray-100 text-gray-700';
          const isClosed = deal.stage.includes('closed');
          return (
            <Card key={deal.id} className={cn('hover:shadow-md transition-shadow cursor-pointer', isClosed && 'opacity-60')} onClick={() => setLocation(`/crm/deals/${deal.id}`)}>
              <CardContent className="p-4">
                <div className="flex items-center justify-between">
                  <div className="min-w-0 flex-1">
                    <div className="flex items-center gap-2"><p className="text-sm font-semibold text-gray-900 truncate">{deal.name}</p><Badge className={`text-[10px] shrink-0 ${stageCls}`}>{fmtLabel(deal.stage)}</Badge></div>
                    <div className="flex items-center gap-4 mt-1 text-xs text-gray-500">
                      {deal.value && <span className="font-medium text-gray-700">{fmtCurrency(deal.value)}</span>}
                      {deal.probability != null && <span>{deal.probability}%</span>}
                      {deal.expectedCloseDate && <span>Close: {fmtDate(deal.expectedCloseDate)}</span>}
                    </div>
                    {deal.probability != null && !isClosed && <Progress value={deal.probability} className="h-1 mt-2" />}
                  </div>
                  <ChevronRight className="h-4 w-4 text-gray-400 shrink-0 ml-3" />
                </div>
              </CardContent>
            </Card>
          );
        })}
      </div>
    </div>
  );
}
