uploads = []
generated = []

[[outputs]]
id = "J_2A-LxFy___RKWZE4MfB"
uri = "file://analysis-section.zip"
type = "unspecified"
title = "MarinaMatch — Analysis Section (147 files, 576KB)"

[[outputs]]
id = "DtBmOicQZAeGL44m5nxqZ"
uri = "file://marinamatch-export.zip"
type = "unspecified"
title = "MarinaMatch — Full Source Code (53 files, 232KB)"
