export const PL_TO_PROFORMA_MAP: Record<string, string> = {
  'gross_potential_rent': 'income.gross_potential_rent',
  'vacancy_loss': 'income.vacancy_credit',
  'concessions': 'income.concessions',
  'bad_debt': 'income.bad_debt',
  'effective_gross_income': 'income.effective_gross_income',
  'parking_income': 'income.other.parking',
  'laundry_income': 'income.other.laundry',
  'late_fees': 'income.other.late_fees',
  'pet_fees': 'income.other.pet_fees',
  'storage_income': 'income.other.storage',
  'utility_reimbursements': 'income.other.utility_reimbursements',
  'total_other_income': 'income.other_income_total',
  'total_revenue': 'income.total_revenue',
  'management_fees': 'expenses.management',
  'payroll': 'expenses.payroll',
  'repairs_maintenance': 'expenses.repairs_maintenance',
  'contract_services': 'expenses.contract_services',
  'utilities': 'expenses.utilities',
  'insurance': 'expenses.insurance',
  'real_estate_taxes': 'expenses.real_estate_taxes',
  'landscaping': 'expenses.landscaping',
  'administrative': 'expenses.administrative',
  'advertising_marketing': 'expenses.advertising_marketing',
  'reserves': 'expenses.reserves',
  'total_operating_expenses': 'expenses.total_opex',
  'net_operating_income': 'summary.noi',
  'mortgage_payment': 'debt.mortgage_payment',
  'interest_expense': 'debt.interest_expense',
  'net_cash_flow': 'summary.net_cash_flow',
};

export const RENT_ROLL_TO_PROFORMA_MAP: Record<string, string> = {
  'total_units': 'property.total_units',
  'occupancy_rate': 'property.current_occupancy',
  'total_actual_rent': 'income.gross_potential_rent',
  'total_potential_rent': 'income.potential_gross_rent',
  'total_sqft': 'property.total_sqft',
  'occupied_units': 'property.occupied_units',
  'vacant_units': 'property.vacant_units',
};

export const FIELD_DISPLAY_LABELS: Record<string, string> = {
  gross_potential_rent: 'Gross Potential Rent',
  vacancy_loss: 'Vacancy Loss',
  concessions: 'Concessions',
  bad_debt: 'Bad Debt',
  effective_gross_income: 'Effective Gross Income',
  parking_income: 'Parking Income',
  laundry_income: 'Laundry Income',
  late_fees: 'Late Fees',
  pet_fees: 'Pet Fees',
  storage_income: 'Storage Income',
  utility_reimbursements: 'Utility Reimbursements',
  total_other_income: 'Total Other Income',
  total_revenue: 'Total Revenue',
  management_fees: 'Management Fees',
  payroll: 'Payroll & Benefits',
  repairs_maintenance: 'Repairs & Maintenance',
  contract_services: 'Contract Services',
  utilities: 'Utilities',
  insurance: 'Insurance',
  real_estate_taxes: 'Real Estate Taxes',
  landscaping: 'Landscaping',
  administrative: 'Administrative',
  advertising_marketing: 'Advertising & Marketing',
  reserves: 'Reserves',
  total_operating_expenses: 'Total Operating Expenses',
  net_operating_income: 'Net Operating Income',
  mortgage_payment: 'Mortgage Payment',
  interest_expense: 'Interest Expense',
  principal_payment: 'Principal Payment',
  net_cash_flow: 'Net Cash Flow',
  total_units: 'Total Units',
  total_sqft: 'Total Square Footage',
  occupancy_rate: 'Occupancy Rate',
  occupied_units: 'Occupied Units',
  vacant_units: 'Vacant Units',
  total_actual_rent: 'Total Actual Rent',
  total_potential_rent: 'Total Potential Rent',
};

export const FIELD_GROUPS: Record<string, string> = {
  gross_potential_rent: 'income',
  vacancy_loss: 'income',
  concessions: 'income',
  bad_debt: 'income',
  effective_gross_income: 'income',
  parking_income: 'other_income',
  laundry_income: 'other_income',
  late_fees: 'other_income',
  pet_fees: 'other_income',
  storage_income: 'other_income',
  utility_reimbursements: 'other_income',
  total_other_income: 'other_income',
  total_revenue: 'income',
  management_fees: 'expenses',
  payroll: 'expenses',
  repairs_maintenance: 'expenses',
  contract_services: 'expenses',
  utilities: 'expenses',
  insurance: 'expenses',
  real_estate_taxes: 'expenses',
  landscaping: 'expenses',
  administrative: 'expenses',
  advertising_marketing: 'expenses',
  reserves: 'expenses',
  total_operating_expenses: 'expenses',
  net_operating_income: 'summary',
  mortgage_payment: 'debt',
  interest_expense: 'debt',
  principal_payment: 'debt',
  net_cash_flow: 'summary',
  total_units: 'summary',
  total_sqft: 'summary',
  occupancy_rate: 'summary',
  occupied_units: 'summary',
  vacant_units: 'summary',
  total_actual_rent: 'income',
  total_potential_rent: 'income',
};
