import { z } from 'zod';
export declare const liv2Sources: import("drizzle-orm/pg-core").PgTableWithColumns<{
    name: "liv2_sources";
    schema: undefined;
    columns: {
        id: import("drizzle-orm/pg-core").PgColumn<{
            name: "id";
            tableName: "liv2_sources";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: true;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        name: import("drizzle-orm/pg-core").PgColumn<{
            name: "name";
            tableName: "liv2_sources";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        domain: import("drizzle-orm/pg-core").PgColumn<{
            name: "domain";
            tableName: "liv2_sources";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        type: import("drizzle-orm/pg-core").PgColumn<{
            name: "type";
            tableName: "liv2_sources";
            dataType: "string";
            columnType: "PgText";
            data: "html" | "api";
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {
            $type: "html" | "api";
        }>;
        rules: import("drizzle-orm/pg-core").PgColumn<{
            name: "rules";
            tableName: "liv2_sources";
            dataType: "json";
            columnType: "PgJsonb";
            data: Liv2SourceRules;
            driverParam: unknown;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {
            $type: Liv2SourceRules;
        }>;
        isActive: import("drizzle-orm/pg-core").PgColumn<{
            name: "is_active";
            tableName: "liv2_sources";
            dataType: "boolean";
            columnType: "PgBoolean";
            data: boolean;
            driverParam: boolean;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        createdAt: import("drizzle-orm/pg-core").PgColumn<{
            name: "created_at";
            tableName: "liv2_sources";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        updatedAt: import("drizzle-orm/pg-core").PgColumn<{
            name: "updated_at";
            tableName: "liv2_sources";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
export declare const liv2ScrapeRuns: import("drizzle-orm/pg-core").PgTableWithColumns<{
    name: "liv2_scrape_runs";
    schema: undefined;
    columns: {
        id: import("drizzle-orm/pg-core").PgColumn<{
            name: "id";
            tableName: "liv2_scrape_runs";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: true;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        sourceId: import("drizzle-orm/pg-core").PgColumn<{
            name: "source_id";
            tableName: "liv2_scrape_runs";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        startedAt: import("drizzle-orm/pg-core").PgColumn<{
            name: "started_at";
            tableName: "liv2_scrape_runs";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        completedAt: import("drizzle-orm/pg-core").PgColumn<{
            name: "completed_at";
            tableName: "liv2_scrape_runs";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        status: import("drizzle-orm/pg-core").PgColumn<{
            name: "status";
            tableName: "liv2_scrape_runs";
            dataType: "string";
            columnType: "PgText";
            data: "partial" | "failed" | "running" | "success";
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {
            $type: "partial" | "failed" | "running" | "success";
        }>;
        metrics: import("drizzle-orm/pg-core").PgColumn<{
            name: "metrics";
            tableName: "liv2_scrape_runs";
            dataType: "json";
            columnType: "PgJsonb";
            data: Liv2RunMetrics;
            driverParam: unknown;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {
            $type: Liv2RunMetrics;
        }>;
        createdAt: import("drizzle-orm/pg-core").PgColumn<{
            name: "created_at";
            tableName: "liv2_scrape_runs";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
export declare const liv2RawPages: import("drizzle-orm/pg-core").PgTableWithColumns<{
    name: "liv2_raw_pages";
    schema: undefined;
    columns: {
        id: import("drizzle-orm/pg-core").PgColumn<{
            name: "id";
            tableName: "liv2_raw_pages";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: true;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        runId: import("drizzle-orm/pg-core").PgColumn<{
            name: "run_id";
            tableName: "liv2_raw_pages";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        sourceId: import("drizzle-orm/pg-core").PgColumn<{
            name: "source_id";
            tableName: "liv2_raw_pages";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        url: import("drizzle-orm/pg-core").PgColumn<{
            name: "url";
            tableName: "liv2_raw_pages";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        finalUrl: import("drizzle-orm/pg-core").PgColumn<{
            name: "final_url";
            tableName: "liv2_raw_pages";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        statusCode: import("drizzle-orm/pg-core").PgColumn<{
            name: "status_code";
            tableName: "liv2_raw_pages";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        fetchedAt: import("drizzle-orm/pg-core").PgColumn<{
            name: "fetched_at";
            tableName: "liv2_raw_pages";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        headers: import("drizzle-orm/pg-core").PgColumn<{
            name: "headers";
            tableName: "liv2_raw_pages";
            dataType: "json";
            columnType: "PgJsonb";
            data: Record<string, string>;
            driverParam: unknown;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {
            $type: Record<string, string>;
        }>;
        bodyHash: import("drizzle-orm/pg-core").PgColumn<{
            name: "body_hash";
            tableName: "liv2_raw_pages";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        html: import("drizzle-orm/pg-core").PgColumn<{
            name: "html";
            tableName: "liv2_raw_pages";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        error: import("drizzle-orm/pg-core").PgColumn<{
            name: "error";
            tableName: "liv2_raw_pages";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
export declare const liv2ListingCandidates: import("drizzle-orm/pg-core").PgTableWithColumns<{
    name: "liv2_listing_candidates";
    schema: undefined;
    columns: {
        id: import("drizzle-orm/pg-core").PgColumn<{
            name: "id";
            tableName: "liv2_listing_candidates";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: true;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        runId: import("drizzle-orm/pg-core").PgColumn<{
            name: "run_id";
            tableName: "liv2_listing_candidates";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        sourceId: import("drizzle-orm/pg-core").PgColumn<{
            name: "source_id";
            tableName: "liv2_listing_candidates";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        url: import("drizzle-orm/pg-core").PgColumn<{
            name: "url";
            tableName: "liv2_listing_candidates";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        canonicalUrl: import("drizzle-orm/pg-core").PgColumn<{
            name: "canonical_url";
            tableName: "liv2_listing_candidates";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        stableSourceKey: import("drizzle-orm/pg-core").PgColumn<{
            name: "stable_source_key";
            tableName: "liv2_listing_candidates";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        identityConfidence: import("drizzle-orm/pg-core").PgColumn<{
            name: "identity_confidence";
            tableName: "liv2_listing_candidates";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        canonicalListingId: import("drizzle-orm/pg-core").PgColumn<{
            name: "canonical_listing_id";
            tableName: "liv2_listing_candidates";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        discoveredAt: import("drizzle-orm/pg-core").PgColumn<{
            name: "discovered_at";
            tableName: "liv2_listing_candidates";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        status: import("drizzle-orm/pg-core").PgColumn<{
            name: "status";
            tableName: "liv2_listing_candidates";
            dataType: "string";
            columnType: "PgText";
            data: "pending" | "error" | "extracted" | "quarantined";
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {
            $type: "pending" | "error" | "extracted" | "quarantined";
        }>;
        reason: import("drizzle-orm/pg-core").PgColumn<{
            name: "reason";
            tableName: "liv2_listing_candidates";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
export declare const liv2ListingPayloads: import("drizzle-orm/pg-core").PgTableWithColumns<{
    name: "liv2_listing_payloads";
    schema: undefined;
    columns: {
        id: import("drizzle-orm/pg-core").PgColumn<{
            name: "id";
            tableName: "liv2_listing_payloads";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: true;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        canonicalListingId: import("drizzle-orm/pg-core").PgColumn<{
            name: "canonical_listing_id";
            tableName: "liv2_listing_payloads";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        sourceId: import("drizzle-orm/pg-core").PgColumn<{
            name: "source_id";
            tableName: "liv2_listing_payloads";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        extractedAt: import("drizzle-orm/pg-core").PgColumn<{
            name: "extracted_at";
            tableName: "liv2_listing_payloads";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        extractorVersion: import("drizzle-orm/pg-core").PgColumn<{
            name: "extractor_version";
            tableName: "liv2_listing_payloads";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        payload: import("drizzle-orm/pg-core").PgColumn<{
            name: "payload";
            tableName: "liv2_listing_payloads";
            dataType: "json";
            columnType: "PgJsonb";
            data: ListingPayloadV2;
            driverParam: unknown;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {
            $type: ListingPayloadV2;
        }>;
        payloadHash: import("drizzle-orm/pg-core").PgColumn<{
            name: "payload_hash";
            tableName: "liv2_listing_payloads";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        validation: import("drizzle-orm/pg-core").PgColumn<{
            name: "validation";
            tableName: "liv2_listing_payloads";
            dataType: "json";
            columnType: "PgJsonb";
            data: ValidationResult;
            driverParam: unknown;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {
            $type: ValidationResult;
        }>;
    };
    dialect: "pg";
}>;
export declare const liv2ListingAssets: import("drizzle-orm/pg-core").PgTableWithColumns<{
    name: "liv2_listing_assets";
    schema: undefined;
    columns: {
        id: import("drizzle-orm/pg-core").PgColumn<{
            name: "id";
            tableName: "liv2_listing_assets";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: true;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        canonicalListingId: import("drizzle-orm/pg-core").PgColumn<{
            name: "canonical_listing_id";
            tableName: "liv2_listing_assets";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        sourceId: import("drizzle-orm/pg-core").PgColumn<{
            name: "source_id";
            tableName: "liv2_listing_assets";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        assetType: import("drizzle-orm/pg-core").PgColumn<{
            name: "asset_type";
            tableName: "liv2_listing_assets";
            dataType: "string";
            columnType: "PgText";
            data: "image";
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {
            $type: "image";
        }>;
        assetUrl: import("drizzle-orm/pg-core").PgColumn<{
            name: "asset_url";
            tableName: "liv2_listing_assets";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        assetUrlNormalized: import("drizzle-orm/pg-core").PgColumn<{
            name: "asset_url_normalized";
            tableName: "liv2_listing_assets";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        originUrl: import("drizzle-orm/pg-core").PgColumn<{
            name: "origin_url";
            tableName: "liv2_listing_assets";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        contentHash: import("drizzle-orm/pg-core").PgColumn<{
            name: "content_hash";
            tableName: "liv2_listing_assets";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        bytes: import("drizzle-orm/pg-core").PgColumn<{
            name: "bytes";
            tableName: "liv2_listing_assets";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        width: import("drizzle-orm/pg-core").PgColumn<{
            name: "width";
            tableName: "liv2_listing_assets";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        height: import("drizzle-orm/pg-core").PgColumn<{
            name: "height";
            tableName: "liv2_listing_assets";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        verified: import("drizzle-orm/pg-core").PgColumn<{
            name: "verified";
            tableName: "liv2_listing_assets";
            dataType: "boolean";
            columnType: "PgBoolean";
            data: boolean;
            driverParam: boolean;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        verificationReason: import("drizzle-orm/pg-core").PgColumn<{
            name: "verification_reason";
            tableName: "liv2_listing_assets";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        createdAt: import("drizzle-orm/pg-core").PgColumn<{
            name: "created_at";
            tableName: "liv2_listing_assets";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
export declare const liv2Quarantine: import("drizzle-orm/pg-core").PgTableWithColumns<{
    name: "liv2_quarantine";
    schema: undefined;
    columns: {
        id: import("drizzle-orm/pg-core").PgColumn<{
            name: "id";
            tableName: "liv2_quarantine";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: true;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        sourceId: import("drizzle-orm/pg-core").PgColumn<{
            name: "source_id";
            tableName: "liv2_quarantine";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        url: import("drizzle-orm/pg-core").PgColumn<{
            name: "url";
            tableName: "liv2_quarantine";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        canonicalUrl: import("drizzle-orm/pg-core").PgColumn<{
            name: "canonical_url";
            tableName: "liv2_quarantine";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        canonicalListingId: import("drizzle-orm/pg-core").PgColumn<{
            name: "canonical_listing_id";
            tableName: "liv2_quarantine";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        identityConfidence: import("drizzle-orm/pg-core").PgColumn<{
            name: "identity_confidence";
            tableName: "liv2_quarantine";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        payload: import("drizzle-orm/pg-core").PgColumn<{
            name: "payload";
            tableName: "liv2_quarantine";
            dataType: "json";
            columnType: "PgJsonb";
            data: Partial<ListingPayloadV2>;
            driverParam: unknown;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {
            $type: Partial<ListingPayloadV2>;
        }>;
        validation: import("drizzle-orm/pg-core").PgColumn<{
            name: "validation";
            tableName: "liv2_quarantine";
            dataType: "json";
            columnType: "PgJsonb";
            data: ValidationResult;
            driverParam: unknown;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {
            $type: ValidationResult;
        }>;
        reason: import("drizzle-orm/pg-core").PgColumn<{
            name: "reason";
            tableName: "liv2_quarantine";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        createdAt: import("drizzle-orm/pg-core").PgColumn<{
            name: "created_at";
            tableName: "liv2_quarantine";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
export declare const liv2FieldProvenance: import("drizzle-orm/pg-core").PgTableWithColumns<{
    name: "liv2_field_provenance";
    schema: undefined;
    columns: {
        id: import("drizzle-orm/pg-core").PgColumn<{
            name: "id";
            tableName: "liv2_field_provenance";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: true;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        canonicalListingId: import("drizzle-orm/pg-core").PgColumn<{
            name: "canonical_listing_id";
            tableName: "liv2_field_provenance";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        sourceId: import("drizzle-orm/pg-core").PgColumn<{
            name: "source_id";
            tableName: "liv2_field_provenance";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        fieldName: import("drizzle-orm/pg-core").PgColumn<{
            name: "field_name";
            tableName: "liv2_field_provenance";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        fieldValueHash: import("drizzle-orm/pg-core").PgColumn<{
            name: "field_value_hash";
            tableName: "liv2_field_provenance";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        originUrl: import("drizzle-orm/pg-core").PgColumn<{
            name: "origin_url";
            tableName: "liv2_field_provenance";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        extractedAt: import("drizzle-orm/pg-core").PgColumn<{
            name: "extracted_at";
            tableName: "liv2_field_provenance";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        extractorVersion: import("drizzle-orm/pg-core").PgColumn<{
            name: "extractor_version";
            tableName: "liv2_field_provenance";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        createdAt: import("drizzle-orm/pg-core").PgColumn<{
            name: "created_at";
            tableName: "liv2_field_provenance";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
export declare const liv2ListingsCurrent: import("drizzle-orm/pg-core").PgTableWithColumns<{
    name: "liv2_listings_current";
    schema: undefined;
    columns: {
        id: import("drizzle-orm/pg-core").PgColumn<{
            name: "id";
            tableName: "liv2_listings_current";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: true;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        canonicalListingId: import("drizzle-orm/pg-core").PgColumn<{
            name: "canonical_listing_id";
            tableName: "liv2_listings_current";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        sourceId: import("drizzle-orm/pg-core").PgColumn<{
            name: "source_id";
            tableName: "liv2_listings_current";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        domain: import("drizzle-orm/pg-core").PgColumn<{
            name: "domain";
            tableName: "liv2_listings_current";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        title: import("drizzle-orm/pg-core").PgColumn<{
            name: "title";
            tableName: "liv2_listings_current";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        listingType: import("drizzle-orm/pg-core").PgColumn<{
            name: "listing_type";
            tableName: "liv2_listings_current";
            dataType: "string";
            columnType: "PgText";
            data: ListingType;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {
            $type: ListingType;
        }>;
        status: import("drizzle-orm/pg-core").PgColumn<{
            name: "status";
            tableName: "liv2_listings_current";
            dataType: "string";
            columnType: "PgText";
            data: ListingStatus;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {
            $type: ListingStatus;
        }>;
        askingPrice: import("drizzle-orm/pg-core").PgColumn<{
            name: "asking_price";
            tableName: "liv2_listings_current";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        currency: import("drizzle-orm/pg-core").PgColumn<{
            name: "currency";
            tableName: "liv2_listings_current";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        priceType: import("drizzle-orm/pg-core").PgColumn<{
            name: "price_type";
            tableName: "liv2_listings_current";
            dataType: "string";
            columnType: "PgText";
            data: "auction" | "unknown" | "asking";
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {
            $type: "auction" | "unknown" | "asking";
        }>;
        address1: import("drizzle-orm/pg-core").PgColumn<{
            name: "address1";
            tableName: "liv2_listings_current";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        city: import("drizzle-orm/pg-core").PgColumn<{
            name: "city";
            tableName: "liv2_listings_current";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        state: import("drizzle-orm/pg-core").PgColumn<{
            name: "state";
            tableName: "liv2_listings_current";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        postalCode: import("drizzle-orm/pg-core").PgColumn<{
            name: "postal_code";
            tableName: "liv2_listings_current";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        country: import("drizzle-orm/pg-core").PgColumn<{
            name: "country";
            tableName: "liv2_listings_current";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        lat: import("drizzle-orm/pg-core").PgColumn<{
            name: "lat";
            tableName: "liv2_listings_current";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        lng: import("drizzle-orm/pg-core").PgColumn<{
            name: "lng";
            tableName: "liv2_listings_current";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        geoPrecision: import("drizzle-orm/pg-core").PgColumn<{
            name: "geo_precision";
            tableName: "liv2_listings_current";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        description: import("drizzle-orm/pg-core").PgColumn<{
            name: "description";
            tableName: "liv2_listings_current";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        acreage: import("drizzle-orm/pg-core").PgColumn<{
            name: "acreage";
            tableName: "liv2_listings_current";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        waterfrontFeet: import("drizzle-orm/pg-core").PgColumn<{
            name: "waterfront_feet";
            tableName: "liv2_listings_current";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        slips: import("drizzle-orm/pg-core").PgColumn<{
            name: "slips";
            tableName: "liv2_listings_current";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        dryRacks: import("drizzle-orm/pg-core").PgColumn<{
            name: "dry_racks";
            tableName: "liv2_listings_current";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        occupancy: import("drizzle-orm/pg-core").PgColumn<{
            name: "occupancy";
            tableName: "liv2_listings_current";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        capRate: import("drizzle-orm/pg-core").PgColumn<{
            name: "cap_rate";
            tableName: "liv2_listings_current";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        noi: import("drizzle-orm/pg-core").PgColumn<{
            name: "noi";
            tableName: "liv2_listings_current";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        revenue: import("drizzle-orm/pg-core").PgColumn<{
            name: "revenue";
            tableName: "liv2_listings_current";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        yearBuilt: import("drizzle-orm/pg-core").PgColumn<{
            name: "year_built";
            tableName: "liv2_listings_current";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        zoning: import("drizzle-orm/pg-core").PgColumn<{
            name: "zoning";
            tableName: "liv2_listings_current";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        brokerName: import("drizzle-orm/pg-core").PgColumn<{
            name: "broker_name";
            tableName: "liv2_listings_current";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        brokerCompany: import("drizzle-orm/pg-core").PgColumn<{
            name: "broker_company";
            tableName: "liv2_listings_current";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        brokerPhone: import("drizzle-orm/pg-core").PgColumn<{
            name: "broker_phone";
            tableName: "liv2_listings_current";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        brokerEmail: import("drizzle-orm/pg-core").PgColumn<{
            name: "broker_email";
            tableName: "liv2_listings_current";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        heroImageUrl: import("drizzle-orm/pg-core").PgColumn<{
            name: "hero_image_url";
            tableName: "liv2_listings_current";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        imageCount: import("drizzle-orm/pg-core").PgColumn<{
            name: "image_count";
            tableName: "liv2_listings_current";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: false;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        sourceUrl: import("drizzle-orm/pg-core").PgColumn<{
            name: "source_url";
            tableName: "liv2_listings_current";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        canonicalUrl: import("drizzle-orm/pg-core").PgColumn<{
            name: "canonical_url";
            tableName: "liv2_listings_current";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        publishedAt: import("drizzle-orm/pg-core").PgColumn<{
            name: "published_at";
            tableName: "liv2_listings_current";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        lastPayloadHash: import("drizzle-orm/pg-core").PgColumn<{
            name: "last_payload_hash";
            tableName: "liv2_listings_current";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        lastExtractedAt: import("drizzle-orm/pg-core").PgColumn<{
            name: "last_extracted_at";
            tableName: "liv2_listings_current";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        createdAt: import("drizzle-orm/pg-core").PgColumn<{
            name: "created_at";
            tableName: "liv2_listings_current";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        updatedAt: import("drizzle-orm/pg-core").PgColumn<{
            name: "updated_at";
            tableName: "liv2_listings_current";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
export interface Liv2SourceRules {
    contentSelectors?: {
        title?: string;
        price?: string;
        address?: string;
        description?: string;
        gallery?: string;
        broker?: string;
        listingId?: string;
    };
    imageAllowPatterns?: string[];
    urlPatterns?: {
        listing?: string;
        index?: string;
    };
    jsonLdType?: string;
    rateLimit?: {
        requestsPerMinute: number;
        delayMs: number;
    };
}
export interface Liv2RunMetrics {
    pagesDiscovered: number;
    pagesFetched: number;
    pagesFailed: number;
    listingsExtracted: number;
    listingsQuarantined: number;
    imagesProcessed: number;
    imagesVerified: number;
    durationMs: number;
}
export type ListingType = 'marina' | 'rv_park' | 'mixed_use' | 'land' | 'business_only' | 'other';
export type ListingStatus = 'active' | 'under_contract' | 'sold' | 'unknown';
export interface ListingPayloadV2 {
    source: {
        domain: string;
        url: string;
        canonicalUrl: string;
        stableKey?: string;
    };
    identity: {
        canonicalListingId: string;
        confidence: number;
        matchBasis: 'explicit_id' | 'canonical_url' | 'jsonld' | 'address_geo_fallback';
    };
    core: {
        title?: string;
        listingType?: ListingType;
        status?: ListingStatus;
    };
    pricing: {
        price?: {
            amount: number;
            currency: 'USD';
        };
        priceType?: 'asking' | 'auction' | 'unknown';
    };
    location: {
        address1?: string;
        city?: string;
        state?: string;
        postalCode?: string;
        country?: string;
        lat?: number;
        lng?: number;
        geoPrecision?: 'rooftop' | 'range_interpolated' | 'approximate' | 'unknown';
    };
    details: {
        description?: string;
        acreage?: number;
        waterfrontFeet?: number;
        slips?: number;
        dryRacks?: number;
        rackCount?: number;
        occupancy?: number;
        capRate?: number;
        noi?: number;
        revenue?: number;
        yearBuilt?: number;
        zoning?: string;
        parcels?: string[];
    };
    contacts: {
        brokerName?: string;
        brokerCompany?: string;
        brokerPhone?: string;
        brokerEmail?: string;
    };
    media: {
        images: Array<{
            url: string;
            urlNormalized: string;
            verified: boolean;
            contentHash?: string;
        }>;
        heroImageUrl?: string;
    };
    timestamps: {
        scrapedAt: string;
        publishedAt?: string;
        updatedAt?: string;
    };
    meta?: Record<string, unknown>;
}
export interface ValidationResult {
    ok: boolean;
    errors: string[];
    warnings: string[];
}
export declare const insertLiv2SourceSchema: z.ZodObject<Omit<{
    id: z.ZodOptional<z.ZodString>;
    name: z.ZodString;
    domain: z.ZodString;
    type: z.ZodOptional<z.ZodString>;
    rules: z.ZodOptional<z.ZodNullable<z.ZodType<Liv2SourceRules, z.ZodTypeDef, Liv2SourceRules>>>;
    isActive: z.ZodOptional<z.ZodBoolean>;
    createdAt: z.ZodOptional<z.ZodDate>;
    updatedAt: z.ZodOptional<z.ZodDate>;
}, "id" | "createdAt" | "updatedAt">, "strip", z.ZodTypeAny, {
    name: string;
    domain: string;
    isActive?: boolean | undefined;
    type?: string | undefined;
    rules?: Liv2SourceRules | null | undefined;
}, {
    name: string;
    domain: string;
    isActive?: boolean | undefined;
    type?: string | undefined;
    rules?: Liv2SourceRules | null | undefined;
}>;
export declare const insertLiv2ScrapeRunSchema: z.ZodObject<Omit<{
    id: z.ZodOptional<z.ZodString>;
    sourceId: z.ZodString;
    startedAt: z.ZodOptional<z.ZodDate>;
    completedAt: z.ZodOptional<z.ZodNullable<z.ZodDate>>;
    status: z.ZodOptional<z.ZodString>;
    metrics: z.ZodOptional<z.ZodNullable<z.ZodType<Liv2RunMetrics, z.ZodTypeDef, Liv2RunMetrics>>>;
    createdAt: z.ZodOptional<z.ZodDate>;
}, "id" | "createdAt">, "strip", z.ZodTypeAny, {
    sourceId: string;
    metrics?: Liv2RunMetrics | null | undefined;
    status?: string | undefined;
    startedAt?: Date | undefined;
    completedAt?: Date | null | undefined;
}, {
    sourceId: string;
    metrics?: Liv2RunMetrics | null | undefined;
    status?: string | undefined;
    startedAt?: Date | undefined;
    completedAt?: Date | null | undefined;
}>;
export declare const insertLiv2RawPageSchema: z.ZodObject<Omit<{
    id: z.ZodOptional<z.ZodString>;
    runId: z.ZodString;
    sourceId: z.ZodString;
    url: z.ZodString;
    finalUrl: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    statusCode: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    fetchedAt: z.ZodOptional<z.ZodDate>;
    headers: z.ZodOptional<z.ZodNullable<z.ZodType<Record<string, string>, z.ZodTypeDef, Record<string, string>>>>;
    bodyHash: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    html: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    error: z.ZodOptional<z.ZodNullable<z.ZodString>>;
}, "id">, "strip", z.ZodTypeAny, {
    url: string;
    runId: string;
    sourceId: string;
    html?: string | null | undefined;
    error?: string | null | undefined;
    finalUrl?: string | null | undefined;
    statusCode?: number | null | undefined;
    fetchedAt?: Date | undefined;
    headers?: Record<string, string> | null | undefined;
    bodyHash?: string | null | undefined;
}, {
    url: string;
    runId: string;
    sourceId: string;
    html?: string | null | undefined;
    error?: string | null | undefined;
    finalUrl?: string | null | undefined;
    statusCode?: number | null | undefined;
    fetchedAt?: Date | undefined;
    headers?: Record<string, string> | null | undefined;
    bodyHash?: string | null | undefined;
}>;
export declare const insertLiv2ListingCandidateSchema: z.ZodObject<Omit<{
    id: z.ZodOptional<z.ZodString>;
    runId: z.ZodString;
    sourceId: z.ZodString;
    url: z.ZodString;
    canonicalUrl: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    stableSourceKey: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    identityConfidence: z.ZodOptional<z.ZodNumber>;
    canonicalListingId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    discoveredAt: z.ZodOptional<z.ZodDate>;
    status: z.ZodOptional<z.ZodString>;
    reason: z.ZodOptional<z.ZodNullable<z.ZodString>>;
}, "id">, "strip", z.ZodTypeAny, {
    url: string;
    runId: string;
    sourceId: string;
    status?: string | undefined;
    reason?: string | null | undefined;
    discoveredAt?: Date | undefined;
    canonicalUrl?: string | null | undefined;
    stableSourceKey?: string | null | undefined;
    identityConfidence?: number | undefined;
    canonicalListingId?: string | null | undefined;
}, {
    url: string;
    runId: string;
    sourceId: string;
    status?: string | undefined;
    reason?: string | null | undefined;
    discoveredAt?: Date | undefined;
    canonicalUrl?: string | null | undefined;
    stableSourceKey?: string | null | undefined;
    identityConfidence?: number | undefined;
    canonicalListingId?: string | null | undefined;
}>;
export declare const insertLiv2ListingPayloadSchema: z.ZodObject<Omit<{
    id: z.ZodOptional<z.ZodString>;
    canonicalListingId: z.ZodString;
    sourceId: z.ZodString;
    extractedAt: z.ZodOptional<z.ZodDate>;
    extractorVersion: z.ZodOptional<z.ZodString>;
    payload: z.ZodType<ListingPayloadV2, z.ZodTypeDef, ListingPayloadV2>;
    payloadHash: z.ZodString;
    validation: z.ZodOptional<z.ZodNullable<z.ZodType<ValidationResult, z.ZodTypeDef, ValidationResult>>>;
}, "id">, "strip", z.ZodTypeAny, {
    sourceId: string;
    canonicalListingId: string;
    payload: ListingPayloadV2;
    payloadHash: string;
    validation?: ValidationResult | null | undefined;
    extractedAt?: Date | undefined;
    extractorVersion?: string | undefined;
}, {
    sourceId: string;
    canonicalListingId: string;
    payload: ListingPayloadV2;
    payloadHash: string;
    validation?: ValidationResult | null | undefined;
    extractedAt?: Date | undefined;
    extractorVersion?: string | undefined;
}>;
export declare const insertLiv2ListingAssetSchema: z.ZodObject<Omit<{
    id: z.ZodOptional<z.ZodString>;
    canonicalListingId: z.ZodString;
    sourceId: z.ZodString;
    assetType: z.ZodOptional<z.ZodString>;
    assetUrl: z.ZodString;
    assetUrlNormalized: z.ZodString;
    originUrl: z.ZodString;
    contentHash: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    bytes: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    width: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    height: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    verified: z.ZodOptional<z.ZodBoolean>;
    verificationReason: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    createdAt: z.ZodOptional<z.ZodDate>;
}, "id" | "createdAt">, "strip", z.ZodTypeAny, {
    sourceId: string;
    canonicalListingId: string;
    assetUrl: string;
    assetUrlNormalized: string;
    originUrl: string;
    assetType?: string | undefined;
    contentHash?: string | null | undefined;
    bytes?: number | null | undefined;
    width?: number | null | undefined;
    height?: number | null | undefined;
    verified?: boolean | undefined;
    verificationReason?: string | null | undefined;
}, {
    sourceId: string;
    canonicalListingId: string;
    assetUrl: string;
    assetUrlNormalized: string;
    originUrl: string;
    assetType?: string | undefined;
    contentHash?: string | null | undefined;
    bytes?: number | null | undefined;
    width?: number | null | undefined;
    height?: number | null | undefined;
    verified?: boolean | undefined;
    verificationReason?: string | null | undefined;
}>;
export declare const insertLiv2QuarantineSchema: z.ZodObject<Omit<{
    id: z.ZodOptional<z.ZodString>;
    sourceId: z.ZodString;
    url: z.ZodString;
    canonicalUrl: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    canonicalListingId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    identityConfidence: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    payload: z.ZodOptional<z.ZodNullable<z.ZodType<Partial<ListingPayloadV2>, z.ZodTypeDef, Partial<ListingPayloadV2>>>>;
    validation: z.ZodOptional<z.ZodNullable<z.ZodType<ValidationResult, z.ZodTypeDef, ValidationResult>>>;
    reason: z.ZodString;
    createdAt: z.ZodOptional<z.ZodDate>;
}, "id" | "createdAt">, "strip", z.ZodTypeAny, {
    url: string;
    reason: string;
    sourceId: string;
    validation?: ValidationResult | null | undefined;
    canonicalUrl?: string | null | undefined;
    identityConfidence?: number | null | undefined;
    canonicalListingId?: string | null | undefined;
    payload?: Partial<ListingPayloadV2> | null | undefined;
}, {
    url: string;
    reason: string;
    sourceId: string;
    validation?: ValidationResult | null | undefined;
    canonicalUrl?: string | null | undefined;
    identityConfidence?: number | null | undefined;
    canonicalListingId?: string | null | undefined;
    payload?: Partial<ListingPayloadV2> | null | undefined;
}>;
export declare const insertLiv2FieldProvenanceSchema: z.ZodObject<Omit<{
    id: z.ZodOptional<z.ZodString>;
    canonicalListingId: z.ZodString;
    sourceId: z.ZodString;
    fieldName: z.ZodString;
    fieldValueHash: z.ZodString;
    originUrl: z.ZodString;
    extractedAt: z.ZodOptional<z.ZodDate>;
    extractorVersion: z.ZodString;
    createdAt: z.ZodOptional<z.ZodDate>;
}, "id" | "createdAt">, "strip", z.ZodTypeAny, {
    sourceId: string;
    canonicalListingId: string;
    extractorVersion: string;
    originUrl: string;
    fieldName: string;
    fieldValueHash: string;
    extractedAt?: Date | undefined;
}, {
    sourceId: string;
    canonicalListingId: string;
    extractorVersion: string;
    originUrl: string;
    fieldName: string;
    fieldValueHash: string;
    extractedAt?: Date | undefined;
}>;
export type Liv2Source = typeof liv2Sources.$inferSelect;
export type InsertLiv2Source = z.infer<typeof insertLiv2SourceSchema>;
export type Liv2ScrapeRun = typeof liv2ScrapeRuns.$inferSelect;
export type Liv2RawPage = typeof liv2RawPages.$inferSelect;
export type Liv2ListingCandidate = typeof liv2ListingCandidates.$inferSelect;
export type Liv2ListingPayload = typeof liv2ListingPayloads.$inferSelect;
export type Liv2ListingAsset = typeof liv2ListingAssets.$inferSelect;
export type Liv2Quarantine = typeof liv2Quarantine.$inferSelect;
export type Liv2FieldProvenance = typeof liv2FieldProvenance.$inferSelect;
export type Liv2ListingCurrent = typeof liv2ListingsCurrent.$inferSelect;
