#!/usr/bin/env tsx
/**
 * Generate idempotent migration stubs for schema drift.
 *
 * Usage:
 *   npx tsx scripts/generate-startup-migrations.ts           # print stubs only
 *   npx tsx scripts/generate-startup-migrations.ts --apply   # write stubs automatically
 *
 *   Via npm:
 *   npm run gen:migrations                  # print stubs only
 *   npm run gen:migrations -- --apply       # write stubs automatically
 *
 * The script:
 *  1. Scans db/schema-*.ts files and regenerates db/schema-index.ts so that
 *     the barrel stays current for server-side bundling (no manual edits needed).
 *  2. Compares every table and column defined across all schema sources
 *     (shared/schema.ts plus every discovered db/schema-*.ts) against the
 *     entries already present in server/db-startup-migrations.ts and prints
 *     ready-to-paste migration stubs for anything not yet covered.
 *  3. Compares every named index defined in the schema against the
 *     CREATE INDEX IF NOT EXISTS entries already present in
 *     server/db-startup-migrations.ts and prints stubs for missing indexes.
 *
 * Without --apply it prints stubs to stdout so a developer can review and paste
 * them in at the appropriate place.
 *
 * With --apply it writes the stubs directly into server/db-startup-migrations.ts
 * just before the closing `];` of the MIGRATIONS array, prints a summary of what
 * was added, and exits 0. New column stubs use 'text' as a placeholder type —
 * review the file afterwards and adjust PostgreSQL types as needed.
 *
 * Exit codes:
 *   0 — all schema definitions are already covered (or --apply succeeded)
 *   1 — at least one table, column, or index lacks a migration stub (print mode)
 */

import { readFileSync, readdirSync, writeFileSync } from "fs";
import { resolve, join, dirname, basename } from "path";
import { fileURLToPath } from "url";
import { is } from "drizzle-orm";
import { PgTable, Index, getTableConfig } from "drizzle-orm/pg-core";

const __dirname = dirname(fileURLToPath(import.meta.url));
const dbDir = resolve(__dirname, "../db");

// ─── 1. Discover db/schema-*.ts files ─────────────────────────────────────────

let dbEntries: string[] = [];
try {
  dbEntries = readdirSync(dbDir);
} catch {
  // db/ directory doesn't exist — nothing extra to load.
}

const schemaFiles = dbEntries
  .filter((f) => f.startsWith("schema-") && f.endsWith(".ts") && !f.endsWith(".d.ts") && f !== "schema-index.ts")
  .sort();

// ─── 2. Regenerate db/schema-index.ts ─────────────────────────────────────────
//
// Keeps the static barrel that server/schema-drift.ts (and the esbuild bundle)
// rely on in sync with the current set of secondary schema files.
//
// External schema exports (those whose paths don't match ./schema-*) that were
// manually added to the file are detected and preserved verbatim so that the
// regeneration never silently drops them.

/**
 * Given the existing schema-index.ts content, extract any lines (and their
 * immediately-preceding comment lines) that are NOT part of the auto-generated
 * set of db/schema-*.ts exports. These are manually-pinned exports for schemas
 * that live outside the db/ directory.
 */
function extractExternalExportBlock(
  existingContent: string,
  autoGeneratedFiles: string[]
): string {
  // Build a set of the auto-generated export statements so we can skip them.
  const autoExports = new Set(
    autoGeneratedFiles.map((f) => `export * from "./${basename(f, ".ts")}";`)
  );

  const lines = existingContent.split("\n");
  const externalLines: string[] = [];
  let pendingComments: string[] = [];

  for (const line of lines) {
    const trimmed = line.trim();

    // Collect comment lines speculatively — they may precede an external export.
    if (trimmed.startsWith("//")) {
      pendingComments.push(line);
      continue;
    }

    if (trimmed.startsWith("export * from")) {
      if (!autoExports.has(trimmed)) {
        // This is an external (manually-pinned) export.
        externalLines.push(...pendingComments, line);
      }
      pendingComments = [];
      continue;
    }

    // Any other line resets the pending-comment buffer.
    pendingComments = [];
  }

  return externalLines.join("\n");
}

function generateBarrelContent(files: string[], externalBlock: string): string {
  const header = `/**
 * AUTO-GENERATED — do not edit manually.
 *
 * Re-exports every secondary schema defined in db/schema-*.ts so that
 * server-side modules can import them with a single static import that
 * esbuild (and tsc) can analyse and bundle at build time.
 *
 * To regenerate after adding a new db/schema-*.ts file, run:
 *   npx tsx scripts/sync-schema-index.ts
 *
 * The generate-startup-migrations script also regenerates this file
 * automatically whenever it is executed.
 */\n`;

  const autoExports =
    files.length === 0
      ? "// No secondary schema files found."
      : files.map((f) => `export * from "./${basename(f, ".ts")}";`).join("\n");

  const parts = [header, "\n" + autoExports];
  if (externalBlock.trim()) {
    parts.push("\n" + externalBlock);
  }
  return parts.join("\n") + "\n";
}

const indexPath = join(dbDir, "schema-index.ts");
let existingIndexContent = "";
try {
  existingIndexContent = readFileSync(indexPath, "utf8");
} catch {
  // File doesn't exist yet.
}

const externalBlock = extractExternalExportBlock(existingIndexContent, schemaFiles);
const newIndexContent = generateBarrelContent(schemaFiles, externalBlock);

if (newIndexContent !== existingIndexContent) {
  writeFileSync(indexPath, newIndexContent, "utf8");
  console.log(
    `[generate-migrations] Updated db/schema-index.ts (${schemaFiles.length} secondary schema file(s) covered).`
  );
}

// ─── 3. Load all schemas ───────────────────────────────────────────────────────

// tsx resolves TypeScript imports natively; use relative paths without aliases.
const schema = await import("../shared/schema");

/** All schema sources merged into one flat object. */
const allSchemas: Record<string, unknown> = { ...schema };

for (const file of schemaFiles) {
  try {
    const mod = await import(join(dbDir, file));
    Object.assign(allSchemas, mod);
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    console.error(
      `[generate-migrations] FATAL: Could not load secondary schema "${file}": ${msg}\n` +
        `  Fix the import error before running this script.`
    );
    process.exit(1);
  }
}

interface IndexDef {
  indexName: string;
  tableName: string;
  columns: string[];
  unique: boolean;
}

interface TableDef {
  tableName: string;
  columns: string[];
  indexes: IndexDef[];
}

function extractSchemaTables(): TableDef[] {
  const tables: TableDef[] = [];
  const seen = new Set<string>();
  for (const value of Object.values(allSchemas)) {
    if (is(value as object, PgTable)) {
      const config = getTableConfig(value as PgTable);
      if (seen.has(config.name)) continue;
      seen.add(config.name);

      const indexes: IndexDef[] = [];
      for (const idx of config.indexes) {
        if (is(idx, Index) && idx.config.name) {
          // Extract column names from the index config.
          // Each entry in idx.config.columns is either a Column object (with .name)
          // or a SQL expression (no .name). Fall back to a placeholder for expressions.
          const cols = (idx.config.columns as Array<{ name?: string }>)
            .map((c) => c.name ?? "/* expression */");

          indexes.push({
            indexName: idx.config.name,
            tableName: config.name,
            columns: cols,
            unique: (idx.config as { unique?: boolean }).unique ?? false,
          });
        }
      }

      tables.push({
        tableName: config.name,
        columns: config.columns.map((c) => c.name),
        indexes,
      });
    }
  }
  return tables;
}

// ─── 4. Parse what is already covered in db-startup-migrations.ts ─────────────

const migrationsFilePath = resolve(
  __dirname,
  "../server/db-startup-migrations.ts"
);
const migrationsSource = readFileSync(migrationsFilePath, "utf8");

/**
 * Build a Set of "table.column" keys that are already addressed by an
 * ADD COLUMN entry in the migrations file, a Set of table names that have
 * a CREATE TABLE entry (meaning all columns are considered covered), and
 * a Set of index names that are already covered by a CREATE INDEX entry.
 */
function parseCoveredItems(): {
  coveredColumns: Set<string>;
  coveredTables: Set<string>;
  coveredIndexes: Set<string>;
} {
  const coveredColumns = new Set<string>();
  const coveredTables = new Set<string>();
  const coveredIndexes = new Set<string>();

  // Match: ALTER TABLE <table> ADD COLUMN IF NOT EXISTS <column>
  const addColRe =
    /ALTER\s+TABLE\s+(\w+)\s+ADD\s+COLUMN\s+IF\s+NOT\s+EXISTS\s+(\w+)/gi;
  for (const m of migrationsSource.matchAll(addColRe)) {
    coveredColumns.add(`${m[1].toLowerCase()}.${m[2].toLowerCase()}`);
  }

  // Match: CREATE TABLE IF NOT EXISTS <table>
  const createTableRe = /CREATE\s+TABLE\s+IF\s+NOT\s+EXISTS\s+(\w+)/gi;
  for (const m of migrationsSource.matchAll(createTableRe)) {
    coveredTables.add(m[1].toLowerCase());
  }

  // Match: CREATE [UNIQUE] INDEX IF NOT EXISTS <indexName>
  const createIndexRe =
    /CREATE\s+(?:UNIQUE\s+)?INDEX\s+IF\s+NOT\s+EXISTS\s+(\w+)/gi;
  for (const m of migrationsSource.matchAll(createIndexRe)) {
    coveredIndexes.add(m[1].toLowerCase());
  }

  return { coveredColumns, coveredTables, coveredIndexes };
}

// ─── 5. Compare and generate stubs ───────────────────────────────────────────

const schemaTables = extractSchemaTables();
const { coveredColumns, coveredTables, coveredIndexes } = parseCoveredItems();

let missingColumnCount = 0;
let missingIndexCount = 0;
const columnOutputLines: string[] = [];
const indexOutputLines: string[] = [];

for (const { tableName, columns, indexes } of schemaTables) {
  const tableKey = tableName.toLowerCase();

  // ── Column stubs ────────────────────────────────────────────────────────────
  if (!coveredTables.has(tableKey)) {
    const missingColumns = columns.filter(
      (col) => !coveredColumns.has(`${tableKey}.${col.toLowerCase()}`)
    );

    if (missingColumns.length > 0) {
      columnOutputLines.push(`\n  // ${tableName} — uncovered columns`);
      for (const col of missingColumns) {
        columnOutputLines.push(
          `  { name: "${tableName}: add ${col}", sql: \`ALTER TABLE ${tableName} ADD COLUMN IF NOT EXISTS ${col} text\` },`
        );
        missingColumnCount++;
      }
    }
  }

  // ── Index stubs ─────────────────────────────────────────────────────────────
  const missingIndexes = indexes.filter(
    (idx) => !coveredIndexes.has(idx.indexName.toLowerCase())
  );

  if (missingIndexes.length > 0) {
    indexOutputLines.push(`\n  // ${tableName} — uncovered indexes`);
    for (const idx of missingIndexes) {
      const keyword = idx.unique ? "UNIQUE INDEX" : "INDEX";
      const colList = idx.columns.join(", ");
      indexOutputLines.push(
        `  { name: "${tableName}: add index ${idx.indexName}", sql: \`CREATE ${keyword} IF NOT EXISTS ${idx.indexName} ON ${tableName} (${colList})\` },`
      );
      missingIndexCount++;
    }
  }
}

// ─── 6. Report / Auto-apply ───────────────────────────────────────────────────

const totalMissing = missingColumnCount + missingIndexCount;
const applyMode = process.argv.includes("--apply");

if (totalMissing === 0) {
  console.log(
    "[generate-migrations] All schema tables, columns, and indexes are already covered — nothing to add."
  );
  process.exit(0);
}

// Build the combined stub block that will be inserted (or printed).
const allStubLines = [...columnOutputLines, ...indexOutputLines];
const stubBlock = allStubLines.join("\n");

if (applyMode) {
  // ── Auto-apply: insert stubs before the closing `];` of MIGRATIONS ──────────
  const marker = "\n];";
  const insertionIdx = migrationsSource.lastIndexOf(marker);
  if (insertionIdx === -1) {
    console.error(
      "[generate-migrations] ERROR: Could not locate the closing `];` of the MIGRATIONS array in server/db-startup-migrations.ts.\n" +
        "  Please paste the stubs manually."
    );
    process.exit(1);
  }

  const updatedSource =
    migrationsSource.slice(0, insertionIdx) +
    "\n" +
    stubBlock +
    migrationsSource.slice(insertionIdx);

  writeFileSync(migrationsFilePath, updatedSource, "utf8");

  console.log(
    `[generate-migrations] Auto-applied ${totalMissing} stub(s) to server/db-startup-migrations.ts.\n`
  );

  if (missingColumnCount > 0) {
    console.log(`  + ${missingColumnCount} ADD COLUMN stub(s)`);
  }
  if (missingIndexCount > 0) {
    console.log(`  + ${missingIndexCount} CREATE INDEX stub(s)`);
  }

  console.log("\n─".repeat(72));
  console.log(stubBlock);
  console.log("─".repeat(72));
  console.log(
    "\nNOTE: The stubs use 'text' as a placeholder type for new columns.\n" +
      "      Review server/db-startup-migrations.ts and adjust PostgreSQL types as needed."
  );

  process.exit(0);
}

// ── Print-only mode (default) ────────────────────────────────────────────────

if (missingColumnCount > 0) {
  console.log(
    `[generate-migrations] Found ${missingColumnCount} column(s) with no migration stub.\n`
  );
  console.log(
    "Paste the following ADD COLUMN entries into the MIGRATIONS array in server/db-startup-migrations.ts."
  );
  console.log(
    "Adjust the PostgreSQL type (currently 'text') to match the actual column type.\n"
  );
  console.log("─".repeat(72));
  for (const line of columnOutputLines) {
    console.log(line);
  }
  console.log("─".repeat(72));
  console.log(
    `\n${missingColumnCount} column stub(s) generated. Review types, then paste into MIGRATIONS.\n`
  );
}

if (missingIndexCount > 0) {
  console.log(
    `[generate-migrations] Found ${missingIndexCount} index(es) with no migration stub.\n`
  );
  console.log(
    "Paste the following CREATE INDEX entries into the MIGRATIONS array in server/db-startup-migrations.ts.\n"
  );
  console.log("─".repeat(72));
  for (const line of indexOutputLines) {
    console.log(line);
  }
  console.log("─".repeat(72));
  console.log(
    `\n${missingIndexCount} index stub(s) generated. Review and paste into MIGRATIONS.`
  );
}

console.log(
  "\nTip: run with --apply to write these stubs automatically:\n" +
    "  npm run gen:migrations -- --apply"
);

process.exit(1);
