#!/usr/bin/env node
/**
 * Seed Stripe Products and Prices for Marketplace+ and Broker subscription SKUs.
 *
 * Idempotent — looks up existing products by metadata tag `marinamatch_sku`
 * before creating. Safe to re-run.
 *
 * Usage:
 *   STRIPE_SECRET_KEY=sk_live_... node scripts/seed_stripe_broker_skus.mjs
 *
 * Outputs the resulting price IDs as environment variable assignments that can
 * be pasted into .env.
 */

import Stripe from "stripe";

const secret = process.env.STRIPE_SECRET_KEY;
if (!secret) {
  console.error("ERROR: STRIPE_SECRET_KEY env var is required.");
  process.exit(1);
}

const stripe = new Stripe(secret);

/**
 * SKU definitions — each becomes one Product with a monthly + annual Price.
 * `sku` is the metadata tag used for idempotent lookup.
 * `envPrefix` is the env var prefix the price IDs will be emitted under.
 */
const SKUS = [
  {
    sku: "marketplace_plus_solo",
    name: "Marketplace+ Solo",
    description: "Expanded Deal Marketplace features and broker follow capacity for individual buyers.",
    monthlyCents: 2400,
    annualCents: 24000,
    envPrefix: "STRIPE_PRICE_MARKETPLACE_PLUS_SOLO",
  },
  {
    sku: "marketplace_plus_pro",
    name: "Marketplace+ Pro",
    description: "Unlimited broker follows, early access, off-market alerts, and messaging.",
    monthlyCents: 6900,
    annualCents: 69000,
    envPrefix: "STRIPE_PRICE_MARKETPLACE_PLUS_PRO",
  },
  {
    sku: "broker_starter",
    name: "Broker Starter",
    description: "Public profile, claim listings, 25 published listings, 1 advisory package.",
    monthlyCents: 7900,
    annualCents: 79000,
    envPrefix: "STRIPE_PRICE_BROKER_STARTER",
  },
  {
    sku: "broker_pro",
    name: "Broker Pro",
    description: "Unlimited listings, 3 advisory packages, featured placement, lead routing, full analytics.",
    monthlyCents: 19900,
    annualCents: 199000,
    envPrefix: "STRIPE_PRICE_BROKER_PRO",
  },
  {
    sku: "broker_enterprise",
    name: "Broker Enterprise",
    description: "Up to 5 seats, unlimited advisory packages, white-label, API access, dedicated CSM.",
    monthlyCents: 49900,
    annualCents: 499000,
    envPrefix: "STRIPE_PRICE_BROKER_ENTERPRISE",
  },
];

async function findProductBySku(sku) {
  // Stripe search API — use metadata tag
  const result = await stripe.products.search({
    query: `metadata['marinamatch_sku']:'${sku}' AND active:'true'`,
    limit: 1,
  });
  return result.data[0] || null;
}

async function findPriceByLookupKey(lookupKey) {
  const result = await stripe.prices.list({
    lookup_keys: [lookupKey],
    active: true,
    limit: 1,
  });
  return result.data[0] || null;
}

async function upsertProduct(spec) {
  let product = await findProductBySku(spec.sku);
  if (product) {
    console.error(`[skip] product ${spec.sku} already exists: ${product.id}`);
    return product;
  }
  product = await stripe.products.create({
    name: spec.name,
    description: spec.description,
    metadata: { marinamatch_sku: spec.sku },
  });
  console.error(`[created] product ${spec.sku}: ${product.id}`);
  return product;
}

async function upsertPrice({ product, spec, interval, amount }) {
  const lookupKey = `${spec.sku}_${interval}`;
  let price = await findPriceByLookupKey(lookupKey);
  if (price) {
    console.error(`[skip] price ${lookupKey} already exists: ${price.id}`);
    return price;
  }
  price = await stripe.prices.create({
    product: product.id,
    currency: "usd",
    unit_amount: amount,
    recurring: { interval },
    lookup_key: lookupKey,
    metadata: { marinamatch_sku: spec.sku, billing_cycle: interval === "year" ? "annual" : "monthly" },
  });
  console.error(`[created] price ${lookupKey}: ${price.id}`);
  return price;
}

async function main() {
  const envLines = [];
  envLines.push("# MarinaMatch Stripe price IDs — generated by seed_stripe_broker_skus.mjs");
  envLines.push("# Copy these into your .env (or the Replit Secrets panel).");
  envLines.push("");

  for (const spec of SKUS) {
    const product = await upsertProduct(spec);

    const monthly = await upsertPrice({
      product,
      spec,
      interval: "month",
      amount: spec.monthlyCents,
    });
    const annual = await upsertPrice({
      product,
      spec,
      interval: "year",
      amount: spec.annualCents,
    });

    envLines.push(`${spec.envPrefix}_MONTHLY=${monthly.id}`);
    envLines.push(`${spec.envPrefix}_ANNUAL=${annual.id}`);
  }

  console.error("");
  console.error("Done. Resulting env vars:");
  console.error("");
  // Emit machine-readable output to stdout
  for (const line of envLines) {
    process.stdout.write(line + "\n");
  }
}

main().catch((err) => {
  console.error("seed_stripe_broker_skus.mjs failed:", err);
  process.exit(1);
});
