import { db } from '../db';
import {
  rentRolls,
  rentRollEntries,
  rentRollSnapshots,
  rentRollSnapshotDetails,
  budgetRentRollBindings,
  marinaBudgets,
  marinaBudgetActuals,
  marinaBudgetLineItems,
} from '@shared/schema';
import { eq, and, sql, desc, asc, gte, lte, inArray } from 'drizzle-orm';
import type {
  RentRollSnapshot,
  InsertRentRollSnapshot,
  RentRollSnapshotDetail,
  InsertRentRollSnapshotDetail,
  BudgetRentRollBinding,
  InsertBudgetRentRollBinding,
  UpdateBudgetRentRollBinding,
} from '@shared/schema';

export interface SnapshotAggregation {
  totalUnits: number;
  occupiedUnits: number;
  vacantUnits: number;
  occupancyRate: number;
  grossPotentialRevenue: number;
  occupiedRevenue: number;
  vacancyLoss: number;
  averageMonthlyRate: number;
  revenuePerUnit: number;
  byCategory: {
    categoryType: string;
    categoryValue: string;
    unitCount: number;
    occupiedCount: number;
    grossRevenue: number;
    actualRevenue: number;
    averageRate: number;
  }[];
}

export interface SnapshotComparison {
  current: RentRollSnapshot;
  previous: RentRollSnapshot | null;
  changes: {
    occupancyChange: number | null;
    revenueChange: number | null;
    revenueChangePercent: number | null;
    avgRateChange: number | null;
  };
}

export interface PortfolioAggregation {
  totalAssets: number;
  totalUnits: number;
  totalOccupied: number;
  avgOccupancyRate: number;
  totalGrossPotential: number;
  totalActualRevenue: number;
  totalVacancyLoss: number;
  avgRevenuePerUnit: number;
  byAsset: {
    ownedAssetId: string;
    assetName?: string;
    snapshot: RentRollSnapshot | null;
  }[];
}

export class RentRollSnapshotService {
  async computeAggregation(rentRollId: string, orgId: string): Promise<SnapshotAggregation> {
    const entries = await db
      .select()
      .from(rentRollEntries)
      .where(
        and(
          eq(rentRollEntries.rentRollId, rentRollId),
          eq(rentRollEntries.orgId, orgId)
        )
      );

    const totalUnits = entries.length;
    const occupiedUnits = entries.filter(e => e.status === 'active').length;
    const vacantUnits = totalUnits - occupiedUnits;
    const occupancyRate = totalUnits > 0 ? (occupiedUnits / totalUnits) * 100 : 0;

    let grossPotentialRevenue = 0;
    let occupiedRevenue = 0;

    entries.forEach(entry => {
      const rate = Number(entry.monthlyRate) || 0;
      grossPotentialRevenue += rate;
      if (entry.status === 'active') {
        occupiedRevenue += rate;
      }
    });

    const vacancyLoss = grossPotentialRevenue - occupiedRevenue;
    const averageMonthlyRate = totalUnits > 0 ? grossPotentialRevenue / totalUnits : 0;
    const revenuePerUnit = occupiedUnits > 0 ? occupiedRevenue / occupiedUnits : 0;

    const categoryMap = new Map<string, {
      unitCount: number;
      occupiedCount: number;
      grossRevenue: number;
      actualRevenue: number;
    }>();

    entries.forEach(entry => {
      const key = `entry_type:${entry.entryType}`;
      const existing = categoryMap.get(key) || {
        unitCount: 0,
        occupiedCount: 0,
        grossRevenue: 0,
        actualRevenue: 0,
      };

      existing.unitCount++;
      if (entry.status === 'active') {
        existing.occupiedCount++;
        existing.actualRevenue += Number(entry.monthlyRate) || 0;
      }
      existing.grossRevenue += Number(entry.monthlyRate) || 0;

      categoryMap.set(key, existing);
    });

    const byCategory = Array.from(categoryMap.entries()).map(([key, data]) => {
      const [categoryType, categoryValue] = key.split(':');
      return {
        categoryType,
        categoryValue,
        ...data,
        averageRate: data.occupiedCount > 0 ? data.actualRevenue / data.occupiedCount : 0,
      };
    });

    return {
      totalUnits,
      occupiedUnits,
      vacantUnits,
      occupancyRate,
      grossPotentialRevenue,
      occupiedRevenue,
      vacancyLoss,
      averageMonthlyRate,
      revenuePerUnit,
      byCategory,
    };
  }

  async createSnapshot(
    orgId: string,
    rentRollId: string,
    snapshotMonth: number,
    snapshotYear: number,
    ownedAssetId?: string,
    isAutoGenerated = true
  ): Promise<RentRollSnapshot> {
    const aggregation = await this.computeAggregation(rentRollId, orgId);

    const existing = await db
      .select()
      .from(rentRollSnapshots)
      .where(
        and(
          eq(rentRollSnapshots.rentRollId, rentRollId),
          eq(rentRollSnapshots.snapshotYear, snapshotYear),
          eq(rentRollSnapshots.snapshotMonth, snapshotMonth)
        )
      )
      .limit(1);

    let snapshot: RentRollSnapshot;

    if (existing.length > 0) {
      [snapshot] = await db
        .update(rentRollSnapshots)
        .set({
          totalUnits: aggregation.totalUnits,
          occupiedUnits: aggregation.occupiedUnits,
          vacantUnits: aggregation.vacantUnits,
          occupancyRate: String(aggregation.occupancyRate),
          grossPotentialRevenue: String(aggregation.grossPotentialRevenue),
          occupiedRevenue: String(aggregation.occupiedRevenue),
          vacancyLoss: String(aggregation.vacancyLoss),
          averageMonthlyRate: String(aggregation.averageMonthlyRate),
          revenuePerUnit: String(aggregation.revenuePerUnit),
          updatedAt: new Date(),
        })
        .where(eq(rentRollSnapshots.id, existing[0].id))
        .returning();

      await db
        .delete(rentRollSnapshotDetails)
        .where(eq(rentRollSnapshotDetails.snapshotId, snapshot.id));
    } else {
      [snapshot] = await db
        .insert(rentRollSnapshots)
        .values({
          orgId,
          rentRollId,
          ownedAssetId: ownedAssetId || null,
          snapshotMonth,
          snapshotYear,
          totalUnits: aggregation.totalUnits,
          occupiedUnits: aggregation.occupiedUnits,
          vacantUnits: aggregation.vacantUnits,
          occupancyRate: String(aggregation.occupancyRate),
          grossPotentialRevenue: String(aggregation.grossPotentialRevenue),
          occupiedRevenue: String(aggregation.occupiedRevenue),
          vacancyLoss: String(aggregation.vacancyLoss),
          averageMonthlyRate: String(aggregation.averageMonthlyRate),
          revenuePerUnit: String(aggregation.revenuePerUnit),
          isAutoGenerated,
        })
        .returning();
    }

    if (aggregation.byCategory.length > 0) {
      await db.insert(rentRollSnapshotDetails).values(
        aggregation.byCategory.map(cat => ({
          snapshotId: snapshot.id,
          categoryType: cat.categoryType,
          categoryValue: cat.categoryValue,
          unitCount: cat.unitCount,
          occupiedCount: cat.occupiedCount,
          grossRevenue: String(cat.grossRevenue),
          actualRevenue: String(cat.actualRevenue),
          averageRate: String(cat.averageRate),
        }))
      );
    }

    return snapshot;
  }

  async getSnapshot(snapshotId: string, orgId: string): Promise<RentRollSnapshot | null> {
    const [snapshot] = await db
      .select()
      .from(rentRollSnapshots)
      .where(
        and(
          eq(rentRollSnapshots.id, snapshotId),
          eq(rentRollSnapshots.orgId, orgId)
        )
      )
      .limit(1);

    return snapshot || null;
  }

  async getSnapshotsForRentRoll(
    rentRollId: string,
    orgId: string,
    options?: { startYear?: number; startMonth?: number; endYear?: number; endMonth?: number }
  ): Promise<RentRollSnapshot[]> {
    let query = db
      .select()
      .from(rentRollSnapshots)
      .where(
        and(
          eq(rentRollSnapshots.rentRollId, rentRollId),
          eq(rentRollSnapshots.orgId, orgId)
        )
      );

    return query.orderBy(
      desc(rentRollSnapshots.snapshotYear),
      desc(rentRollSnapshots.snapshotMonth)
    );
  }

  async getSnapshotDetails(snapshotId: string): Promise<RentRollSnapshotDetail[]> {
    return db
      .select()
      .from(rentRollSnapshotDetails)
      .where(eq(rentRollSnapshotDetails.snapshotId, snapshotId));
  }

  async compareSnapshots(
    currentSnapshotId: string,
    previousSnapshotId: string | null,
    orgId: string
  ): Promise<SnapshotComparison> {
    const current = await this.getSnapshot(currentSnapshotId, orgId);
    if (!current) {
      throw new Error('Current snapshot not found');
    }

    let previous: RentRollSnapshot | null = null;
    if (previousSnapshotId) {
      previous = await this.getSnapshot(previousSnapshotId, orgId);
    }

    const changes: SnapshotComparison['changes'] = {
      occupancyChange: null,
      revenueChange: null,
      revenueChangePercent: null,
      avgRateChange: null,
    };

    if (previous) {
      const currentOcc = Number(current.occupancyRate) || 0;
      const prevOcc = Number(previous.occupancyRate) || 0;
      changes.occupancyChange = currentOcc - prevOcc;

      const currentRev = Number(current.occupiedRevenue) || 0;
      const prevRev = Number(previous.occupiedRevenue) || 0;
      changes.revenueChange = currentRev - prevRev;
      changes.revenueChangePercent = prevRev > 0 ? ((currentRev - prevRev) / prevRev) * 100 : null;

      const currentAvg = Number(current.averageMonthlyRate) || 0;
      const prevAvg = Number(previous.averageMonthlyRate) || 0;
      changes.avgRateChange = currentAvg - prevAvg;
    }

    return { current, previous, changes };
  }

  async getTimeSeries(
    rentRollId: string,
    orgId: string,
    startYear: number,
    startMonth: number,
    endYear: number,
    endMonth: number
  ): Promise<RentRollSnapshot[]> {
    const startPeriod = startYear * 100 + startMonth;
    const endPeriod = endYear * 100 + endMonth;

    const snapshots = await db
      .select()
      .from(rentRollSnapshots)
      .where(
        and(
          eq(rentRollSnapshots.rentRollId, rentRollId),
          eq(rentRollSnapshots.orgId, orgId)
        )
      );

    return snapshots
      .filter(s => {
        const period = s.snapshotYear * 100 + s.snapshotMonth;
        return period >= startPeriod && period <= endPeriod;
      })
      .sort((a, b) => {
        const periodA = a.snapshotYear * 100 + a.snapshotMonth;
        const periodB = b.snapshotYear * 100 + b.snapshotMonth;
        return periodA - periodB;
      });
  }

  async getPortfolioAggregation(
    orgId: string,
    snapshotYear: number,
    snapshotMonth: number,
    ownedAssetIds?: string[]
  ): Promise<PortfolioAggregation> {
    let query = db
      .select()
      .from(rentRollSnapshots)
      .where(
        and(
          eq(rentRollSnapshots.orgId, orgId),
          eq(rentRollSnapshots.snapshotYear, snapshotYear),
          eq(rentRollSnapshots.snapshotMonth, snapshotMonth),
          ownedAssetIds ? inArray(rentRollSnapshots.ownedAssetId, ownedAssetIds) : undefined
        )
      );

    const snapshots = await query;

    const assetSnapshots = new Map<string, RentRollSnapshot>();
    snapshots.forEach(s => {
      if (s.ownedAssetId) {
        const existing = assetSnapshots.get(s.ownedAssetId);
        if (!existing || s.updatedAt > existing.updatedAt) {
          assetSnapshots.set(s.ownedAssetId, s);
        }
      }
    });

    let totalUnits = 0;
    let totalOccupied = 0;
    let totalGrossPotential = 0;
    let totalActualRevenue = 0;
    let totalVacancyLoss = 0;

    assetSnapshots.forEach(snapshot => {
      totalUnits += snapshot.totalUnits;
      totalOccupied += snapshot.occupiedUnits;
      totalGrossPotential += Number(snapshot.grossPotentialRevenue) || 0;
      totalActualRevenue += Number(snapshot.occupiedRevenue) || 0;
      totalVacancyLoss += Number(snapshot.vacancyLoss) || 0;
    });

    const avgOccupancyRate = totalUnits > 0 ? (totalOccupied / totalUnits) * 100 : 0;
    const avgRevenuePerUnit = totalOccupied > 0 ? totalActualRevenue / totalOccupied : 0;

    return {
      totalAssets: assetSnapshots.size,
      totalUnits,
      totalOccupied,
      avgOccupancyRate,
      totalGrossPotential,
      totalActualRevenue,
      totalVacancyLoss,
      avgRevenuePerUnit,
      byAsset: Array.from(assetSnapshots.entries()).map(([assetId, snapshot]) => ({
        ownedAssetId: assetId,
        snapshot,
      })),
    };
  }

  async createBinding(data: InsertBudgetRentRollBinding): Promise<BudgetRentRollBinding> {
    const [binding] = await db
      .insert(budgetRentRollBindings)
      .values(data)
      .returning();

    return binding;
  }

  async updateBinding(
    bindingId: string,
    data: UpdateBudgetRentRollBinding
  ): Promise<BudgetRentRollBinding | null> {
    const [binding] = await db
      .update(budgetRentRollBindings)
      .set({ ...data, updatedAt: new Date() })
      .where(eq(budgetRentRollBindings.id, bindingId))
      .returning();

    return binding || null;
  }

  async deleteBinding(bindingId: string): Promise<boolean> {
    const result = await db
      .delete(budgetRentRollBindings)
      .where(eq(budgetRentRollBindings.id, bindingId));

    return (result.rowCount || 0) > 0;
  }

  async getBindingsForBudget(budgetId: string): Promise<BudgetRentRollBinding[]> {
    return db
      .select()
      .from(budgetRentRollBindings)
      .where(eq(budgetRentRollBindings.budgetId, budgetId));
  }

  async syncBudgetActualsFromRentRoll(
    budgetId: string,
    orgId: string,
    month: number,
    year: number
  ): Promise<{ synced: number; errors: string[] }> {
    const [budget] = await db
      .select()
      .from(marinaBudgets)
      .where(
        and(
          eq(marinaBudgets.id, budgetId),
          eq(marinaBudgets.orgId, orgId)
        )
      )
      .limit(1);

    if (!budget) {
      throw new Error('Budget not found');
    }

    if (!budget.rentRollId || !budget.rentRollSyncEnabled) {
      return { synced: 0, errors: ['Budget is not linked to a rent roll or sync is disabled'] };
    }

    const bindings = await this.getBindingsForBudget(budgetId);
    const enabledBindings = bindings.filter(b => b.syncEnabled);

    if (enabledBindings.length === 0) {
      return { synced: 0, errors: ['No enabled bindings found for this budget'] };
    }

    const [snapshot] = await db
      .select()
      .from(rentRollSnapshots)
      .where(
        and(
          eq(rentRollSnapshots.rentRollId, budget.rentRollId),
          eq(rentRollSnapshots.snapshotYear, year),
          eq(rentRollSnapshots.snapshotMonth, month)
        )
      )
      .limit(1);

    if (!snapshot) {
      return { synced: 0, errors: [`No snapshot found for ${month}/${year}`] };
    }

    const details = await this.getSnapshotDetails(snapshot.id);
    const errors: string[] = [];
    let synced = 0;

    for (const binding of enabledBindings) {
      try {
        let actualAmount = 0;

        if (binding.bindingScope === 'overall_storage') {
          actualAmount = Number(snapshot.occupiedRevenue) || 0;
        } else if (binding.bindingScope === 'entry_type' && binding.bindingKey) {
          const detail = details.find(
            d => d.categoryType === 'entry_type' && d.categoryValue === binding.bindingKey
          );
          if (detail) {
            actualAmount = Number(detail.actualRevenue) || 0;
          }
        }

        const existingActual = await db
          .select()
          .from(marinaBudgetActuals)
          .where(
            and(
              eq(marinaBudgetActuals.lineItemId, binding.lineItemId),
              eq(marinaBudgetActuals.year, year),
              eq(marinaBudgetActuals.month, month)
            )
          )
          .limit(1);

        if (existingActual.length > 0) {
          await db
            .update(marinaBudgetActuals)
            .set({
              actualAmount: String(actualAmount),
              source: 'rent_roll',
              sourceId: snapshot.id,
              recordedAt: new Date(),
            })
            .where(eq(marinaBudgetActuals.id, existingActual[0].id));
        } else {
          await db.insert(marinaBudgetActuals).values({
            budgetId,
            lineItemId: binding.lineItemId,
            month,
            year,
            actualAmount: String(actualAmount),
            source: 'rent_roll',
            sourceId: snapshot.id,
          });
        }

        await db
          .update(budgetRentRollBindings)
          .set({
            lastSyncedAt: new Date(),
            syncStatus: 'synced',
          })
          .where(eq(budgetRentRollBindings.id, binding.id));

        synced++;
      } catch (error: any) {
        errors.push(`Failed to sync binding ${binding.id}: ${error.message}`);
        await db
          .update(budgetRentRollBindings)
          .set({ syncStatus: 'error' })
          .where(eq(budgetRentRollBindings.id, binding.id));
      }
    }

    await db
      .update(marinaBudgets)
      .set({ lastRentRollSyncAt: new Date() })
      .where(eq(marinaBudgets.id, budgetId));

    return { synced, errors };
  }
}

export const rentRollSnapshotService = new RentRollSnapshotService();
