export const ROLES = {
  CORPORATE_ADMIN: 'corporate_admin',
  REGIONAL_MANAGER: 'regional_manager', 
  SITE_MANAGER: 'site_manager',
  DOCKMASTER: 'dockmaster',
  STAFF: 'staff',
  CUSTOMER: 'customer',
  GUEST: 'guest',
} as const;

export type Role = typeof ROLES[keyof typeof ROLES];

export const ROLE_HIERARCHY: Record<Role, number> = {
  [ROLES.CORPORATE_ADMIN]: 100,
  [ROLES.REGIONAL_MANAGER]: 80,
  [ROLES.SITE_MANAGER]: 60,
  [ROLES.DOCKMASTER]: 40,
  [ROLES.STAFF]: 20,
  [ROLES.CUSTOMER]: 10,
  [ROLES.GUEST]: 0,
};

export const PERMISSIONS = {
  VIEW_DASHBOARD: 'view_dashboard',
  VIEW_FINANCIAL_REPORTS: 'view_financial_reports',
  MANAGE_BILLING: 'manage_billing',
  MANAGE_PAYMENTS: 'manage_payments',
  
  VIEW_CUSTOMERS: 'view_customers',
  CREATE_CUSTOMER: 'create_customer',
  EDIT_CUSTOMER: 'edit_customer',
  DELETE_CUSTOMER: 'delete_customer',
  
  VIEW_BOATS: 'view_boats',
  CREATE_BOAT: 'create_boat',
  EDIT_BOAT: 'edit_boat',
  DELETE_BOAT: 'delete_boat',
  
  VIEW_SLIPS: 'view_slips',
  MANAGE_SLIPS: 'manage_slips',
  
  VIEW_LAUNCHES: 'view_launches',
  CREATE_LAUNCH: 'create_launch',
  MANAGE_LAUNCHES: 'manage_launches',
  
  VIEW_RESERVATIONS: 'view_reservations',
  CREATE_RESERVATION: 'create_reservation',
  MANAGE_RESERVATIONS: 'manage_reservations',
  
  VIEW_LEASES: 'view_leases',
  CREATE_LEASE: 'create_lease',
  MANAGE_LEASES: 'manage_leases',
  
  VIEW_CONTRACTS: 'view_contracts',
  CREATE_CONTRACT: 'create_contract',
  MANAGE_CONTRACTS: 'manage_contracts',
  
  VIEW_MESSAGES: 'view_messages',
  SEND_MESSAGES: 'send_messages',
  
  MANAGE_STAFF: 'manage_staff',
  MANAGE_ROLES: 'manage_roles',
  
  VIEW_AUDIT_LOG: 'view_audit_log',
  EXPORT_DATA: 'export_data',
  
  MANAGE_INTEGRATIONS: 'manage_integrations',
  MANAGE_PRICING: 'manage_pricing',
  
  VIEW_MARINA: 'view_marina',
  MANAGE_MARINA: 'manage_marina',
  
  VIEW_ORGANIZATION: 'view_organization',
  MANAGE_ORGANIZATION: 'manage_organization',
  
  MANAGE_ALL_MARINAS: 'manage_all_marinas',
  
  VIEW_OWN_ACCOUNT: 'view_own_account',
  EDIT_OWN_ACCOUNT: 'edit_own_account',
} as const;

export type Permission = typeof PERMISSIONS[keyof typeof PERMISSIONS];

export const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  [ROLES.CORPORATE_ADMIN]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_FINANCIAL_REPORTS,
    PERMISSIONS.MANAGE_BILLING,
    PERMISSIONS.MANAGE_PAYMENTS,
    PERMISSIONS.VIEW_CUSTOMERS,
    PERMISSIONS.CREATE_CUSTOMER,
    PERMISSIONS.EDIT_CUSTOMER,
    PERMISSIONS.DELETE_CUSTOMER,
    PERMISSIONS.VIEW_BOATS,
    PERMISSIONS.CREATE_BOAT,
    PERMISSIONS.EDIT_BOAT,
    PERMISSIONS.DELETE_BOAT,
    PERMISSIONS.VIEW_SLIPS,
    PERMISSIONS.MANAGE_SLIPS,
    PERMISSIONS.VIEW_LAUNCHES,
    PERMISSIONS.CREATE_LAUNCH,
    PERMISSIONS.MANAGE_LAUNCHES,
    PERMISSIONS.VIEW_RESERVATIONS,
    PERMISSIONS.CREATE_RESERVATION,
    PERMISSIONS.MANAGE_RESERVATIONS,
    PERMISSIONS.VIEW_LEASES,
    PERMISSIONS.CREATE_LEASE,
    PERMISSIONS.MANAGE_LEASES,
    PERMISSIONS.VIEW_CONTRACTS,
    PERMISSIONS.CREATE_CONTRACT,
    PERMISSIONS.MANAGE_CONTRACTS,
    PERMISSIONS.VIEW_MESSAGES,
    PERMISSIONS.SEND_MESSAGES,
    PERMISSIONS.MANAGE_STAFF,
    PERMISSIONS.MANAGE_ROLES,
    PERMISSIONS.VIEW_AUDIT_LOG,
    PERMISSIONS.EXPORT_DATA,
    PERMISSIONS.MANAGE_INTEGRATIONS,
    PERMISSIONS.MANAGE_PRICING,
    PERMISSIONS.VIEW_MARINA,
    PERMISSIONS.MANAGE_MARINA,
    PERMISSIONS.VIEW_ORGANIZATION,
    PERMISSIONS.MANAGE_ORGANIZATION,
    PERMISSIONS.MANAGE_ALL_MARINAS,
    PERMISSIONS.VIEW_OWN_ACCOUNT,
    PERMISSIONS.EDIT_OWN_ACCOUNT,
  ],
  [ROLES.REGIONAL_MANAGER]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_FINANCIAL_REPORTS,
    PERMISSIONS.MANAGE_BILLING,
    PERMISSIONS.MANAGE_PAYMENTS,
    PERMISSIONS.VIEW_CUSTOMERS,
    PERMISSIONS.CREATE_CUSTOMER,
    PERMISSIONS.EDIT_CUSTOMER,
    PERMISSIONS.VIEW_BOATS,
    PERMISSIONS.CREATE_BOAT,
    PERMISSIONS.EDIT_BOAT,
    PERMISSIONS.VIEW_SLIPS,
    PERMISSIONS.MANAGE_SLIPS,
    PERMISSIONS.VIEW_LAUNCHES,
    PERMISSIONS.CREATE_LAUNCH,
    PERMISSIONS.MANAGE_LAUNCHES,
    PERMISSIONS.VIEW_RESERVATIONS,
    PERMISSIONS.CREATE_RESERVATION,
    PERMISSIONS.MANAGE_RESERVATIONS,
    PERMISSIONS.VIEW_LEASES,
    PERMISSIONS.CREATE_LEASE,
    PERMISSIONS.MANAGE_LEASES,
    PERMISSIONS.VIEW_CONTRACTS,
    PERMISSIONS.CREATE_CONTRACT,
    PERMISSIONS.MANAGE_CONTRACTS,
    PERMISSIONS.VIEW_MESSAGES,
    PERMISSIONS.SEND_MESSAGES,
    PERMISSIONS.MANAGE_STAFF,
    PERMISSIONS.VIEW_AUDIT_LOG,
    PERMISSIONS.EXPORT_DATA,
    PERMISSIONS.MANAGE_INTEGRATIONS,
    PERMISSIONS.MANAGE_PRICING,
    PERMISSIONS.VIEW_MARINA,
    PERMISSIONS.MANAGE_MARINA,
    PERMISSIONS.VIEW_ORGANIZATION,
    PERMISSIONS.MANAGE_ALL_MARINAS,
    PERMISSIONS.VIEW_OWN_ACCOUNT,
    PERMISSIONS.EDIT_OWN_ACCOUNT,
  ],
  [ROLES.SITE_MANAGER]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_FINANCIAL_REPORTS,
    PERMISSIONS.MANAGE_BILLING,
    PERMISSIONS.MANAGE_PAYMENTS,
    PERMISSIONS.VIEW_CUSTOMERS,
    PERMISSIONS.CREATE_CUSTOMER,
    PERMISSIONS.EDIT_CUSTOMER,
    PERMISSIONS.VIEW_BOATS,
    PERMISSIONS.CREATE_BOAT,
    PERMISSIONS.EDIT_BOAT,
    PERMISSIONS.VIEW_SLIPS,
    PERMISSIONS.MANAGE_SLIPS,
    PERMISSIONS.VIEW_LAUNCHES,
    PERMISSIONS.CREATE_LAUNCH,
    PERMISSIONS.MANAGE_LAUNCHES,
    PERMISSIONS.VIEW_RESERVATIONS,
    PERMISSIONS.CREATE_RESERVATION,
    PERMISSIONS.MANAGE_RESERVATIONS,
    PERMISSIONS.VIEW_LEASES,
    PERMISSIONS.CREATE_LEASE,
    PERMISSIONS.MANAGE_LEASES,
    PERMISSIONS.VIEW_CONTRACTS,
    PERMISSIONS.CREATE_CONTRACT,
    PERMISSIONS.MANAGE_CONTRACTS,
    PERMISSIONS.VIEW_MESSAGES,
    PERMISSIONS.SEND_MESSAGES,
    PERMISSIONS.MANAGE_STAFF,
    PERMISSIONS.EXPORT_DATA,
    PERMISSIONS.MANAGE_INTEGRATIONS,
    PERMISSIONS.MANAGE_PRICING,
    PERMISSIONS.VIEW_MARINA,
    PERMISSIONS.MANAGE_MARINA,
    PERMISSIONS.VIEW_OWN_ACCOUNT,
    PERMISSIONS.EDIT_OWN_ACCOUNT,
  ],
  [ROLES.DOCKMASTER]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_CUSTOMERS,
    PERMISSIONS.CREATE_CUSTOMER,
    PERMISSIONS.EDIT_CUSTOMER,
    PERMISSIONS.VIEW_BOATS,
    PERMISSIONS.CREATE_BOAT,
    PERMISSIONS.EDIT_BOAT,
    PERMISSIONS.VIEW_SLIPS,
    PERMISSIONS.VIEW_LAUNCHES,
    PERMISSIONS.CREATE_LAUNCH,
    PERMISSIONS.MANAGE_LAUNCHES,
    PERMISSIONS.VIEW_RESERVATIONS,
    PERMISSIONS.CREATE_RESERVATION,
    PERMISSIONS.MANAGE_RESERVATIONS,
    PERMISSIONS.VIEW_LEASES,
    PERMISSIONS.VIEW_CONTRACTS,
    PERMISSIONS.CREATE_CONTRACT,
    PERMISSIONS.VIEW_MESSAGES,
    PERMISSIONS.SEND_MESSAGES,
    PERMISSIONS.VIEW_MARINA,
    PERMISSIONS.VIEW_OWN_ACCOUNT,
    PERMISSIONS.EDIT_OWN_ACCOUNT,
  ],
  [ROLES.STAFF]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_CUSTOMERS,
    PERMISSIONS.VIEW_BOATS,
    PERMISSIONS.VIEW_SLIPS,
    PERMISSIONS.VIEW_LAUNCHES,
    PERMISSIONS.CREATE_LAUNCH,
    PERMISSIONS.VIEW_RESERVATIONS,
    PERMISSIONS.VIEW_MESSAGES,
    PERMISSIONS.SEND_MESSAGES,
    PERMISSIONS.VIEW_MARINA,
    PERMISSIONS.VIEW_OWN_ACCOUNT,
    PERMISSIONS.EDIT_OWN_ACCOUNT,
  ],
  [ROLES.CUSTOMER]: [
    PERMISSIONS.VIEW_OWN_ACCOUNT,
    PERMISSIONS.EDIT_OWN_ACCOUNT,
    PERMISSIONS.CREATE_LAUNCH,
    PERMISSIONS.VIEW_LAUNCHES,
    PERMISSIONS.CREATE_RESERVATION,
    PERMISSIONS.VIEW_RESERVATIONS,
    PERMISSIONS.VIEW_MESSAGES,
    PERMISSIONS.SEND_MESSAGES,
  ],
  [ROLES.GUEST]: [
    PERMISSIONS.CREATE_RESERVATION,
    PERMISSIONS.VIEW_RESERVATIONS,
  ],
};

export function hasRole(userRole: Role | undefined, requiredRole: Role): boolean {
  if (!userRole) return false;
  return (ROLE_HIERARCHY[userRole] || 0) >= (ROLE_HIERARCHY[requiredRole] || 0);
}

export function hasPermission(userRole: Role | undefined, permission: Permission): boolean {
  if (!userRole) return false;
  const permissions = ROLE_PERMISSIONS[userRole] || [];
  return permissions.includes(permission);
}

export function hasAnyPermission(userRole: Role | undefined, permissions: Permission[]): boolean {
  return permissions.some(p => hasPermission(userRole, p));
}

export function hasAllPermissions(userRole: Role | undefined, permissions: Permission[]): boolean {
  return permissions.every(p => hasPermission(userRole, p));
}

export function getPermissionsForRole(role: Role): Permission[] {
  return ROLE_PERMISSIONS[role] || [];
}

export function getRoleLabel(role: Role): string {
  const labels: Record<Role, string> = {
    [ROLES.CORPORATE_ADMIN]: 'Corporate Administrator',
    [ROLES.REGIONAL_MANAGER]: 'Regional Manager',
    [ROLES.SITE_MANAGER]: 'Site Manager',
    [ROLES.DOCKMASTER]: 'Dockmaster',
    [ROLES.STAFF]: 'Staff Member',
    [ROLES.CUSTOMER]: 'Customer',
    [ROLES.GUEST]: 'Guest',
  };
  return labels[role] || role;
}

export function getRoleBadgeColor(role: Role): string {
  const colors: Record<Role, string> = {
    [ROLES.CORPORATE_ADMIN]: 'bg-purple-100 text-purple-800 dark:bg-purple-900 dark:text-purple-200',
    [ROLES.REGIONAL_MANAGER]: 'bg-blue-100 text-blue-800 dark:bg-blue-900 dark:text-blue-200',
    [ROLES.SITE_MANAGER]: 'bg-green-100 text-green-800 dark:bg-green-900 dark:text-green-200',
    [ROLES.DOCKMASTER]: 'bg-yellow-100 text-yellow-800 dark:bg-yellow-900 dark:text-yellow-200',
    [ROLES.STAFF]: 'bg-gray-100 text-gray-800 dark:bg-gray-900 dark:text-gray-200',
    [ROLES.CUSTOMER]: 'bg-teal-100 text-teal-800 dark:bg-teal-900 dark:text-teal-200',
    [ROLES.GUEST]: 'bg-slate-100 text-slate-800 dark:bg-slate-900 dark:text-slate-200',
  };
  return colors[role] || 'bg-gray-100 text-gray-800';
}
